### ISSUE TITLE
Swap wNEAR > ETH failed while formatting outputs from RPC

### ISSUE THREAD

**Issue by duyanhnp** [aurora-is-near/aurora-relayer#101]
This issue happens when trying to swap wNEAR to ETH

![2021-10-27_010242](https://user-images.githubusercontent.com/10646367/139114793-8beb5a70-9458-4d50-b324-55a4f39cead1.png)

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
