### ISSUE TITLE
SWAP NEAR TO ETH FAILED

### ISSUE THREAD

**Issue by Banglv89** [aurora-is-near/aurora-relayer#103]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Exceeded the maximum amount of gas allowed to burn per contract.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a5f04d350f7238c-ORD"}}}}'

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
