### ISSUE TITLE
SWAP FAILED

### ISSUE THREAD

**Issue by thiennt6** [aurora-is-near/aurora-relayer#104]
Swap failed: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Exceeded the maximum amount of gas allowed to burn per contract.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a61b8ff013623b0-ORD"}}}}'

<img width="1363" alt="Screen Shot 2021-10-30 at 10 59 02" src="https://user-images.githubusercontent.com/58576835/139519444-733f4bc3-ec08-4213-846f-fea943fffca0.png">

0xe885a9228a8c1626d5dc9e469e14835d846b5a5529e0b2a2ace2019734162fb9

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
