### ISSUE TITLE
Swap failed! 

### ISSUE THREAD

**Issue by floranguyen88** [aurora-is-near/aurora-relayer#105]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Exceeded the maximum amount of gas allowed to burn per contract.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a628b43a71d4c8f-DFW"}}}}'

**Comment by 0x3bfc** [comment]
This is a duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
