### ISSUE TITLE
Swap Near to DAI failed

### ISSUE THREAD

**Issue by quickview357** [aurora-is-near/aurora-relayer#108]
Swap failed: Unknown error: "[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Exceeded the maximum amount of gas allowed to burn per contract.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a773dcbd5b4c6e8-DFW"}}}}'". Try increasing your slippage tolerance.

I'm trying to increase  my slippage tolerance but it does not work.
Work on wallet address 0x226FB96715aB87FA883Ba8Fc0d1C54A34E4C0Ed7

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
