### ISSUE TITLE
Trisolaris swap error (Wnear - Eth)

### ISSUE THREAD

**Issue by DONHND** [aurora-is-near/aurora-relayer#109]
When I switch Wnear to ETH on Trisolaris, this error appears

 Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Exceeded the maximum amount of gas allowed to burn per contract.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a7e95c577d249d2-DFW"}}}}' 

My Near wallet: hoangnd96.near
My aurora wallet: 0x9fB45697950405Efb443D0eadC12C584e43a3cBD

please check it,

**Comment by DONHND** [comment]
![image](https://user-images.githubusercontent.com/93606096/139897928-590148f7-7e21-4eb8-a5b7-c0c5f1b11257.png)

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
