### ISSUE TITLE
Error when swap on trisolaris 

### ISSUE THREAD

**Issue by QuocHa2000** [aurora-is-near/aurora-relayer#112]
I got this error when swap on trisolaris  "Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: Transaction has expired. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a85fdaab47b1924-ORD"}}}}'"

**Comment by QuocHa2000** [comment]
I got another error : "Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - address.substring is not a function. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a86135a944e2398-ORD"}}}}'"

**Comment by 0x3bfc** [comment]
This is not an enough issue description. Feel free to update the issue and reopen it again if you still get these errors.
