### ISSUE TITLE
Error when swapping wNEAR to USDC

### ISSUE THREAD

**Issue by Petrus3n** [aurora-is-near/aurora-relayer#113]
Below is the error message:
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - address.substring is not a function. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a86207d735e49ea-DFW"}}}}'

**Comment by 0x3bfc** [comment]
Please provide more information about the issue. Feel free to reopen it later.
