### ISSUE TITLE
Error when swap Near to ETH at Trisolaris

### ISSUE THREAD

**Issue by zellius-x** [aurora-is-near/aurora-relayer#114]
Error Message
------------
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - \n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a9cf2f067b25646-DFW"}}}}'
--------------

**Comment by 0x3bfc** [comment]
Yes, this was 4 days ago, the issue has been resolved. Feel free to reopen the issue if you still get the same error.
