### ISSUE TITLE
 Swap failed when using trisolaris 

### ISSUE THREAD

**Issue by wumin007git** [aurora-is-near/aurora-relayer#116]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - BadGatewayError: \n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"endpoint:8545","cf-ray":"6a9de099830a6e13-ORD"}}}}'
![image](https://user-images.githubusercontent.com/16831285/140607735-94f4d4a6-4f3f-4a14-8e7d-7ce92de074df.png)

**Comment by 0x3bfc** [comment]
This issue was resolved. Feel free to reopen this issue, if you still get the same error.
