### ISSUE TITLE
Server error: DB Not Found when trying to interact with a contract on testnet

### ISSUE THREAD

**Issue by grishick** [aurora-is-near/aurora-relayer#117]
I am getting this cryptic error in Metamask when trying to interact with my contracts on Aurora testnet:

`MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 70733283 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"testnet.aurora.dev","cf-ray":"6abab0ea61290271-DFW"}}}}' `

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/68
