### ISSUE TITLE
BREAKING: Infinite loop on tx_status_fetch timeouts.

### ISSUE THREAD

**Issue by JonathanLogan** [aurora-is-near/aurora-relayer#126]
Indexer retries tx_status_fetch calls to near for the same object in parallel, and loops infinitely on retry if tx_status_fetch times out.
This starves the indexer and puts high load on near rpc node.
The indexer will fail to produce new blocks. 
Issue is independent on near rpc node in use (official or internal).

**Comment by JonathanLogan** [comment]
{"level":30,"time":1636975632354,"pid":7,"hostname":"f2c444459cca","msg":"resuming from block #52695576"}
{"level":30,"time":1636975632354,"pid":7,"hostname":"f2c444459cca","block":{"id":52695576},"msg":"indexing block #52695576"}
Retrying request to tx as it has timed out [
  '2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1',
  'app.nearcrowd.near'
]
Retrying request to tx as it has timed out [
  '2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1',
  'app.nearcrowd.near'
]
Retrying request to tx as it has timed out [
  '2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1',
  'app.nearcrowd.near'
]
Retrying request to tx as it has timed out [
  '2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1',
  'app.nearcrowd.near'
]
Retrying request to tx as it has timed out [
  '2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1',
  'app.nearcrowd.near'
]
Retrying request to tx as it has timed out [
  '2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1',
  'app.nearcrowd.near'
]
{"level":50,"time":1636975702792,"pid":7,"hostname":"f2c444459cca","msg":"Exceeded 12 attempts for request to tx."}

(it continues to loop on that single transaction, forever)

**Comment by 0x3bfc** [comment]
The relayer only indexes the transaction produced by Aurora EVM. You can check this [line](https://github.com/aurora-is-near/aurora-relayer/blob/82478f35fd12033913f0274fb425608eb0f6fa64/src/indexer.ts#L75) which referring to Aurora's contract Id. However this [tx](https://explorer.mainnet.near.org/transactions/2dwU4Zea1vcNnrLyb4SXCE6Lz1rUYrPY9Z2ugsBocqR1) is a result of interacting with a different contract (app.nearcrowd.near). So I don't understand how this could happen. 

Can you refer where `tx_status_fetch` is called ?

**Comment by artob** [comment]
@0x3bfc To find which block/chunk/transaction has EVM transactions, the indexer needs to fetch every transaction in every chunk. So that's why it's requesting that transaction.

**Comment by JonathanLogan** [comment]
Indexing block #53358622...
Indexing block #53358623...
Indexing block #53358624...
Retrying request to tx as it has timed out [ 'Bppx1jp1vFnYB6JECmnekHsnAS46egQNLGWTUBPjkz83', 'nina2180.near' ]
Retrying request to tx as it has timed out [ '7HupEDoc7fX8d8U4RUJY4ShJsUyYKdyZp1BGdT7NrRvk', 'dsacxz7.near' ]
Retrying request to tx as it has timed out [ '4G5TfS7bnp9rLMsuaETzaQt6dowmaYjMbNbAuU6WSq8n', 'relay.aurora' ]
Retrying request to tx as it has timed out [ '3WPduqJB5BnVJf6J15sbgHzFLmSCNmnx85bphLjeHjVr', 'coin-op.near' ]
Retrying request to tx as it has timed out [ '4NTw1KEyZJJXCtdNDAmsUqQJbJwbdaHWvehQKGAWW2nF', 'hourbq.near' ]
Retrying request to tx as it has timed out [
  '8W5RRkjyst5gvLSEY4jcCWCD2uLaVJvZQDvwgQVarcy9',
  'relayer.bridge.near'
]
Retrying request to tx as it has timed out [
  'HSoky566wmrV4YPsoFudWvKBbk4XN3WxjqoFBUbWc4yE',
  'kristinachirko.near'
]
Retrying request to tx as it has timed out [ 'Bppx1jp1vFnYB6JECmnekHsnAS46egQNLGWTUBPjkz83', 'nina2180.near' ]
Retrying request to tx as it has timed out [ '7HupEDoc7fX8d8U4RUJY4ShJsUyYKdyZp1BGdT7NrRvk', 'dsacxz7.near' ]
Retrying request to tx as it has timed out [ '4G5TfS7bnp9rLMsuaETzaQt6dowmaYjMbNbAuU6WSq8n', 'relay.aurora' ]
Retrying request to tx as it has timed out [ '3WPduqJB5BnVJf6J15sbgHzFLmSCNmnx85bphLjeHjVr', 'coin-op.near' ]
Retrying request to tx as it has timed out [ '4NTw1KEyZJJXCtdNDAmsUqQJbJwbdaHWvehQKGAWW2nF', 'hourbq.near' ]
Retrying request to tx as it has timed out [
  'HSoky566wmrV4YPsoFudWvKBbk4XN3WxjqoFBUbWc4yE',
  'kristinachirko.near'
]

**Comment by 0x3bfc** [comment]
This issue happens prior querying transactions from Near-api ([error msg](https://github.com/near/near-api-js/blob/5c2ea7b41e9be97394ccf15ef7926c592904fa82/src/providers/json-rpc-provider.ts#L377) and the [exponentialBackoff](https://github.com/near/near-api-js/blob/5c2ea7b41e9be97394ccf15ef7926c592904fa82/src/providers/json-rpc-provider.ts#L343)). Thats why it is not easy to reproduce this issue locally. 

The following configurations might affect the issue we experience:
- REQUEST_RETRY_WAIT
- REQUEST_RETRY_NUMBER
- REQUEST_RETRY_WAIT_BACKOFF

**Comment by mfornet** [comment]
This is not an infinite loop, but it is equally bad nonetheless. near-api-js is scheduling several calls at the same time to fetch all txs in the block, and they all fail at the same time, and are retried using exponentialBackoff schedule (12 more times).

The plan discussed with @0x3bfc is to confirm the previous comment using a tunnel where we can see exactly which txs are being sent to the RPC, and what are the responses (including Success/Failure). If we confirm the issue is with how txs are scheduled the plan ahead should be using a different way for scheduling these calls, which might require more discussion and involvement of the near-api-js team.

**Comment by JonathanLogan** [comment]
This is fixed.
