### ISSUE TITLE
Implement Parity's tracing APIs

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-relayer#13]
We have requests from partners to implement Parity's nonstandard tracing APIs, most specifically [`trace_filter`](https://openethereum.github.io/JSONRPC-trace-module#trace_filter), which enable deeper insight into transaction processing.

## References:
- https://openethereum.github.io/JSONRPC-trace-module
- https://docs.alchemyapi.io/alchemy/documentation/alchemy-api-reference/trace-api

**Comment by spilin** [comment]
This repository is deprecated. New repo is [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public). We should reopen this issue in new repo, if it still makes sence.
