### ISSUE TITLE
Sync historical data

### ISSUE THREAD

**Issue by ngxwinter** [aurora-is-near/aurora-relayer#147]
How to actually sync my relayer node? The indexer is only following the head and doesn't go below ~52M block.. So I am trying to make eth_call on some contract and it gives me "Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
". 

So I think its because relayer is missing state for this contract because doesn't have historical blocks. Could you please help me with that?

Thank you

**Comment by 0x3bfc** [comment]
@ngxwinter Can you please provide more info about how to reproduce it ? 

Also would be great to define which 
- network (Aurora Mainnet, Testnet .. )
- block number
- Transaction hash if exist.

**Comment by ngxwinter** [comment]
Well, my question was more about - is there a way to index historical blocks (like 1-2M old) without coding own indexer?
