### ISSUE TITLE
Handling of MetaMask confirmation notifications

### ISSUE THREAD

**Issue by 0x3bfc** [aurora-is-near/aurora-relayer#15]
So far MetaMask works fine with the Aurora RPC only one thing is missing from the UX perspective:

A MetaMask user expects to get confirmation as a browser notification (after confirming the transaction on-chain) prior transaction failing/succeeding.

@artob suggested that `eth_getTransactionReceipt` could solve this issue.

**Comment by 0x3bfc** [comment]
@artob it seems it is blocked by the explorer

**Comment by antonpaisov** [comment]
confirmed with Ahmed, closing
