### ISSUE TITLE
same eth_rpc call, official works, but local fail.

### ISSUE THREAD

**Issue by lhypj** [aurora-is-near/aurora-relayer#150]
here is logs:
`{'jsonrpc': '2.0',
 'id': 1,
 'error': {'code': -32603,
  'message': 'Internal Error - Querying [object Object] failed: wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded)).\n{\n  "error": "wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded))",\n  "logs": [],\n  "block_height": 56165937,\n  "block_hash": "2S1rzTQGx2EiNrUDV4G8hmCALq4e4KRKQts4aasfn19j"\n}. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>',
  'data': {'host': 'aurora-dataseed.defiapp.com'}}}`.

**Comment by 0x3bfc** [comment]
@lhypj  Can you specify which rpc method is failing and how to reproduce your issue ?

**Comment by lhypj** [comment]
> @lhypj Can you specify which rpc method is failing and how to reproduce your issue ?

sorry, It is my fault.

attach file contains it.
[aurora.txt](https://github.com/aurora-is-near/aurora-relayer/files/7786971/aurora.txt)

**Comment by 0x3bfc** [comment]
@lhypj  Please copy/paste it here or on `gist`.

**Comment by lhypj** [comment]
> @lhypj Please copy/paste it here or on `gist`.

{
  "id": 1,
  "method": "eth_call",
  "jsonrpc": "2.0",
  "params": [
    {
      "to": "0x60ad579fb20c8896b7b98e800cba9e196e6eaa44",
      "data": "0x252dba4200000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000032000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000006e00000000000000000000000000000000000000000000000000000000000000780000000000000000000000000000000000000000000000000000000000000082000000000000000000000000000000000000000000000000000000000000008c000000000000000000000000000000000000000000000000000000000000009600000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000aa00000000000000000000000000000000000000000000000000000000000000b400000000000000000000000000000000000000000000000000000000000000be00000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000000d200000000000000000000000000000000000000000000000000000000000000dc00000000000000000000000000000000000000000000000000000000000000e600000000000000000000000000000000000000000000000000000000000000f000000000000000000000000000000000000000000000000000000000000000fa0000000000000000000000000000000000000000000000000000000000000104000000000000000000000000000000000000000000000000000000000000010e00000000000000000000000000000000000000000000000000000000000001180000000000000000000000000000000000000000000000000000000000000122000000000000000000000000000000000000000000000000000000000000012c00000000000000000000000000000000000000000000000000000000000001360000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000014a0000000000000000000000000000000000000000000000000000000000000154000000000000000000000000000000000000000000000000000000000000015e00000000000000000000000000000000000000000000000000000000000001680000000000000000000000000000000000000000000000000000000000000172000000000000000000000000000000000000000000000000000000000000017c00000000000000000000000000000000000000000000000000000000000001860000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000019a00000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000001ae00000000000000000000000000000000000000000000000000000000000001b800000000000000000000000000000000000000000000000000000000000001c200000000000000000000000000000000000000000000000000000000000001cc00000000000000000000000000000000000000000000000000000000000001d600000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000001ea00000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000001fe00000000000000000000000000000000000000000000000000000000000002080000000000000000000000000000000000000000000000000000000000000212000000000000000000000000000000000000000000000000000000000000021c00000000000000000000000000000000000000000000000000000000000002260000000000000000000000000000000000000000000000000000000000000230000000000000000000000000000000000000000000000000000000000000023a0000000000000000000000000000000000000000000000000000000000000244000000000000000000000000000000000000000000000000000000000000024e000000000000000000000000020f8aefb5697b77e0bb835a8518be70775cda1b00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000063da4db6ef4e7c62168ab03982399f9588fcd1980000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000003b666f3488a7992b2385b12df7f35156d7b29cd0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000084b123875f0f36b966d0b6ca14b31121bd9676ad0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000002fe064b6c7d274082aa5d2624709bc9ae7d16c770000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000bc8a244e8fb683ec1fd6f88f3cc6e565082174eb0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000d1654a7713617d41a8c9530fb9b948d00e1621940000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000005eec60f348cb1d661e4a5122cf4638c7db7a886e0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000bf9eef63139b67fd0abf22bd5504acb0519a42120000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000007e9ea10e5984a09d19d05f31ca3cb65bb7df359d0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000f56997948d4235514dcc50fc0ea7c0e110ec255d0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000bf58062d23f869a90c6eb04b9655f0dfca3459470000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000e6c47b036f6fd0684b109b484ac46094e633af2e0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000256d03607eee0156b8a2ab84da1d5b283219fe970000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000bf560771b6002a58477efbcdd6774a5a1947587b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000002e02bea8e9118f7d2ccada1d402286cc6d54bd670000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000003502eac6fa27beebdc5cd3615b7cb0784b0ce48f0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000523fae29d7ff6fd38842c8f271edf2ebd31504350000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000ca461686c711aeaadf0b516f9c2ad9d9b645a9400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000a188d79d6bdbc1120a662de9eb72384e238af1040000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000001fd6cbbfc0363aa394bd77fc74f64009bf54a7e90000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000073155e476d6b857fe7722aefebad50f9f8bd0b380000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000063b4a0538ce8d90876b201af1020d13308a8b2530000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000c374776cf5c497adeef6b505588b00cb298531fd0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000b53bc2537e641c37c7b7a8d33aba1b30283cda2f0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000bd59171da1c3a2624d60421bcb6c3c32701116560000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000f623c32828b40c89d5cf114a7186c6b8b25de4ed0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000fc258cf7f1bf3739a04992d1c790af20d60f44e90000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000001e686d65031ac75754cd6aeab5b71ac2257c6a9d0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000023d4874f30292b24512b969dc8dc8a3227d20120000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000f49803db604e118f3afcf44beb0012f3c6684f050000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000006494dcfa6af36ce89a990ca13911365f006898ae0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000004add83c7a0aed64468a149da583f1b92d1aca6aa0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000004550b283d30f96a8b56fe16eb576f6d5033addf70000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000b87c8a9c77e3c98adca0e24dce5d9f43e2b698bb0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000cb7f715c4cab533b245c070b58628b4d6a4019e00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000004ddac2bff3746adac32e355f1855fd67cc6faa2b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000090e28d422aeac1011e03713125fb9ba6b4276fc80000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000639a02651557ffc1c7f233334248c4e7d416d60b0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000006379f3801cc2004c6cead7d766f5d4279e1789530000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000007b659258a57a5f4db9c4049d01b6d8aaf6400a250000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000c6c7481d7e030ac3acbfd53f98797e32824a7b700000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000006791325d64318bbce35392da6bdff94840c4a4b50000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000ecda075c31c20449f89dc4467cf70d5f98e657d20000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000cf59208abbae8457f39f961eab6293bdef1e5f1e0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb850000000000000000000000000000000000000000000000000000000000000000000000000000000086950b9668804154bd385ae0e228099c4375feea0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000004d2fe5bcc9d3d252383d32e1fff3b3c279eb4e850000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000004f83d6ae3401f6859b579d840a5e38862a8892820000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb85000000000000000000000000000000000000000000000000000000000000000000000000000000006401ded5d808ee824791dbfc23aa8769b585eb370000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000000000000000000000000000c773ef9ae52ff43031dd2db439966ef4cb55bd790000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002470a082310000000000000000000000005853ed4f26a3fcea565b3fbc698bb19cdf6deb8500000000000000000000000000000000000000000000000000000000"
    },
    "latest"
  ]
}

**Comment by aguirrel** [comment]
any update?

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
