### ISSUE TITLE
eth_getBlockByNumber fails with latest in ethClient

### ISSUE THREAD

**Issue by trajan0x** [aurora-is-near/aurora-relayer#152]
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' https://mainnet.aurora.dev/`

returns invalid method parameters

**Comment by spilin** [comment]
`curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' https://mainnet.aurora.dev/`

please try this one
