### ISSUE TITLE
Error: `Exceeded the maximum amount of gas allowed to burn per contract`

### ISSUE THREAD

**Issue by think-in-universe** [aurora-is-near/aurora-relayer#155]
As reported by developers working on multi-chain environment, an operation that costs around 600K Gas will cause the `Exceeded the maximum amount of gas allowed to burn per contract` error when executing the operation on Aurora, which works on other platforms.

**Comment by spilin** [comment]
We are constantly working on increasing gas limit. Recent improvements are already live on testnet. Please check.
