### ISSUE TITLE
Aurora RPC `403 Forbidden` error when exceeds gas limit twice

### ISSUE THREAD

**Issue by think-in-universe** [aurora-is-near/aurora-relayer#156]
As reported by the developer who met the issue #155 , the RPC will return `403 Forbidden` if they met the `Exceeded the maximum amount of gas allowed to burn per contract` error twice.

**Comment by danielwpz** [comment]
For me the 403 errors occurs when I sent a bunch of requests to aurora rpc, it seems I got rate limited by rpc gateway, no matter whether I met the gas issue or not.
 
Is the rpc rate limiting too strict? Once I hit the limit and IP got blocked, it won't recover after several days. That totally blocks me from working on aurora.

**Comment by xtools-at** [comment]
same here, after a botched deployment, i need to cycle my IP to be able to access the RPC again. very annoying when working on the deployer script and hitting this by accident.

**Comment by panukettu** [comment]
yup experiencing the same issue, need to cycle IP's all the time

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
