### ISSUE TITLE
How to access websocket?

### ISSUE THREAD

**Issue by prasad-kumkar** [aurora-is-near/aurora-relayer#157]
I am able to run the relayer and try HTTP query on `http://localhost:8545`, where can I find ws port for the same?

**Comment by spilin** [comment]
sockets are available on `ws://localhost:8545`
if you have `wscat` installed, you can test them it `wscat -c ws://localhost:8545`

**Comment by prasad-kumkar** [comment]
I'm trying to use it for our chainlink node, so passing in this endpoint from relayer should work right?

**Comment by spilin** [comment]
yes, should work

**Comment by prasad-kumkar** [comment]
@spilin It runs fine with HTTP 
But, we're getting 405 on WS
![image](https://user-images.githubusercontent.com/43164022/148524697-81dfb96e-e84f-4ea4-b718-fafd575d4953.png)

So it failed in chainlink too
![image](https://user-images.githubusercontent.com/43164022/148525232-a07a5a93-d288-4ace-b4af-8960190c9ab1.png)

**Comment by spilin** [comment]
Hm.. Are you using latest version of relayer from github?
Please confirm that there is `lib/ws_server.js` file present?



![image](https://user-images.githubusercontent.com/509031/148584590-023271e0-0102-40db-a355-4b828a724363.png)

**Comment by prasad-kumkar** [comment]
There is a lib/ws_server.js file and looks like I'm using the latest version 


Here are the logs when I start docker-compose--
![image](https://user-images.githubusercontent.com/43164022/148594564-133cebde-bd87-411f-873c-82a1cf3d6ed7.png)


I see this log when I send ws connection request - 
```testnet_endpoint | {"level":30,"time":1641582527919,"pid":10,"hostname":"3780a730bcf7","req":{"id":"KT8PFzdCzPTdDQjr","method":"GET","url":"/","headers":{"sec-websocket-version":"13","sec-websocket-key":"K3XesUu2IQf6RtiFUqoWkA==","connection":"Upgrade","upgrade":"websocket","sec-websocket-extensions":"permessage-deflate; client_max_window_bits","host":"localhost:8545"},"remoteAddress":"::ffff:172.18.0.1","remotePort":41054},"res":{"statusCode":405,"headers":{"x-request-id":"KT8PFzdCzPTdDQjr","access-control-allow-origin":"*","allow":"POST"}},"responseTime":5,"msg":"request completed"}```

Here are my configs -
testnet.yaml
```
---
port: 8545
database: postgres://aurora:aurora@database/aurora
network: testnet
endpoint: https://archival-rpc.testnet.near.org
engine: aurora
signer: relay.aurora
writable: true
```

local.yaml
```
signer: test1.chainscore.testnet
signerKey: config/test1.chainscore.testnet.json
```

**Comment by spilin** [comment]
@prasad-kumkar 
Tnx for the information. For testing purposes can you please modify `docker-compose.yaml`  and try running `docker-compose up` again.
Changes:
Line 5: from `image: auroraisnear/relayer-database` to `image: auroraisnear/relayer-database:testnet`
Line 13 and 30 from `image: auroraisnear/relayer-endpoint` to `image: auroraisnear/relayer-endpoint:testnet`

**Comment by prasad-kumkar** [comment]
Made the changes, now I'm getting 
```
root@mainnet-nodes:~/evm/aurora-relayer# wscat -c ws://localhost:8545
error: connect ECONNREFUSED 127.0.0.1:8545
```

And I could see this in docker-compose logs
```
testnet_indexer | Indexing transaction 0x5c1c35b5a5815e4a3fb692f197a00b278e533716c9584c73a46faee08d80a5d1 at #78060860:0...
testnet_database | 2022-01-07 21:42:05.257 UTC [37] ERROR:  column "from" of relation "event" does not exist at character 50
testnet_database | 2022-01-07 21:42:05.257 UTC [37] STATEMENT:  INSERT INTO event ("transaction", "index", data, "from", topics) VALUES ($1, $2, $3, $4, $5)
testnet_indexer | Indexing log event at #78060860:0:0...
testnet_indexer | indexEvent error: column "from" of relation "event" does not exist
testnet_indexer |     at Parser.parseErrorMessage (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:287:98)
testnet_indexer |     at Parser.handlePacket (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:126:29)
testnet_indexer |     at Parser.parse (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:39:38)
testnet_indexer |     at Socket.<anonymous> (/srv/aurora/relayer/node_modules/pg-protocol/dist/index.js:11:42)
testnet_indexer |     at Socket.emit (node:events:390:28)
testnet_indexer |     at addChunk (node:internal/streams/readable:315:12)
testnet_indexer |     at readableAddChunk (node:internal/streams/readable:289:9)
testnet_indexer |     at Socket.Readable.push (node:internal/streams/readable:228:10)
testnet_indexer |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
```
```
testnet_database | 2022-01-07 21:42:06.795 UTC [68] ERROR:  relation "subscription" does not exist at character 63
testnet_database | 2022-01-07 21:42:06.795 UTC [68] STATEMENT:  SELECT sec_websocket_key AS ws_key, id AS sub_id, filter FROM subscription WHERE type = $1
testnet_database | 2022-01-07 21:42:06.797 UTC [68] ERROR:  relation "subscription" does not exist at character 63
testnet_database | 2022-01-07 21:42:06.797 UTC [68] STATEMENT:  SELECT sec_websocket_key AS ws_key, id AS sub_id, filter FROM subscription WHERE type = $1
testnet_endpoint | /srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:287
testnet_endpoint |         const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
testnet_endpoint |                                                                                                  ^
testnet_endpoint | 
testnet_endpoint | error: relation "subscription" does not exist
testnet_endpoint |     at Parser.parseErrorMessage (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:287:98)
testnet_endpoint |     at Parser.handlePacket (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:126:29)
testnet_endpoint |     at Parser.parse (/srv/aurora/relayer/node_modules/pg-protocol/dist/parser.js:39:38)
testnet_endpoint |     at Socket.<anonymous> (/srv/aurora/relayer/node_modules/pg-protocol/dist/index.js:11:42)
testnet_endpoint |     at Socket.emit (node:events:390:28)
testnet_endpoint |     at addChunk (node:internal/streams/readable:315:12)
testnet_endpoint |     at readableAddChunk (node:internal/streams/readable:289:9)
testnet_endpoint |     at Socket.Readable.push (node:internal/streams/readable:228:10)
testnet_endpoint |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {```

**Comment by spilin** [comment]
Can you please do a fresh install. Removing exisiting docker container/volume and running `docker-compose up` usually enough.

**Comment by prasad-kumkar** [comment]
@spilin  that worked! Thank you
I was trying removing the existing container before but didn't realize the volumes were still there. Now I removed both container and volumes and restarted, and it worked

**Comment by prasad-kumkar** [comment]
Does this work for mainnet too?
I'm trying -
Line 5: from image: auroraisnear/relayer-database to image: auroraisnear/relayer-database:mainnet
Line 13 and 30 from image: auroraisnear/relayer-endpoint to image: auroraisnear/relayer-endpoint:mainnet

But that doesn't seem to work

**Comment by spilin** [comment]
you need to use auroraisnear/relayer-database:testnet for both testnet and mainnet for now.
