### ISSUE TITLE
Swap failed

### ISSUE THREAD

**Issue by SVNikolyuk** [aurora-is-near/aurora-relayer#159]
https://www.trisolaris.io/#/swap

Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - FetchError: invalid json response body at http://192.168.1.89:3030/ reason: Unexpected end of JSON input. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"relayer002.backend.internal.aurora.dev","cf-ray":"6ccf280893e913c6-IAD"}}}}'

**Comment by drinkthere** [comment]
The same error occurred on my transaction

**Comment by daichuanliang** [comment]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - blacklist(...).has is not a function. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"jp-1284.sevenblk.com:49963"}}}}'

**Comment by daichuanliang** [comment]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - blacklist(...).has is not a function. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"jp-1284.sevenblk.com:49963"}}}}'

**Comment by daichuanliang** [comment]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - blacklist(...).has is not a function. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"<my aurora rpc>"}}}}'

**Comment by JonathanLogan** [comment]
please copy the file .contrib/blacklist.yaml to the config directory. That should fix it.
