### ISSUE TITLE
Implement eth_estimateGas

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-relayer#16]
Currently, `eth_estimateGas` just returns zero. This leads to MetaMask, for example, suggesting the minimum gas limit of 21000, which is too low for most things: meaning the user will have to manually adjust the limit, negatively affecting UX.

**Comment by juampiq6** [comment]
What's the status of this? We are implementing aurora on our wallet, and could benefit a lot from a better gas estimation. Currently all transaction estimate 6,721,975 as gasLimit (as latest commit linked here) which enables functionality but its not the desired output (especially when sending/swapping max amounts of aETH or when having little amounts of it for broadcasting simple transactions). Is it a problem regarding the relation between an EVM opcode gas usage and an actual WASM instruction from NEAR?
