### ISSUE TITLE
Cannot connect to Aurora RPC, manually or otherwise

### ISSUE THREAD

**Issue by athenachu13** [aurora-is-near/aurora-relayer#160]
Hi, I've been using Aurora for weeks now with no issues. All of a sudden I can no longer connect to the network. it kept showing errors. at first I thought the network was just slow so I didn't think much of it. 

it's been two days now. and I just found out that other people are using the network just fine.

I checked my RPC network settings and tri
<img width="985" alt="Screen Shot 2022-01-15 at 
<img width="575" alt="Screen Shot 2022-01-15 at 9 39 14 AM" src="https://user-images.githubusercontent.com/97795224/149625755-83efb4b6-829b-499e-af7f-ed140c19da2a.png">
9 38 27 AM" src="https://user-images.githubusercontent.com/97795224/149625699-617170dd-1fd8-41ef-83a4-1710d52c624d.png">
ed to reconnect and this is the error I received (see screenshot). 

I also tried the 1-click method via chainlist.org but that didnt work either (see screenshot)/

I have zero ETH in this wallet. is that the issue? gas has been free so it hasn't been an issue before.... 

let me know please. see screenshots.

**Comment by spilin** [comment]
Hi @athenachu13. Can you please confirm if this issue is resolved for you?

**Comment by athenachu13** [comment]
hi,

issue is resolved
