### ISSUE TITLE
Error on harvest from TRI-USDT farm

### ISSUE THREAD

**Issue by noobtgb** [aurora-is-near/aurora-relayer#161]
Unlocked metamask wallet, wallet already connected.
Navigated to https://www.trisolaris.io/#/farm/1.
Clicked "Manage" button for the TRI-USDT farm where LP tokens are farming.
Clicked "Claim" button to claim farmed TRI.
Harvest failed with the following message:

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - FetchError: invalid json response body at http://192.168.1.89:3030/ reason: Unexpected end of JSON input. Please report a bug at ","data":{"host":"relayer005.backend.internal.aurora.dev","cf-ray":"6cebf035513054ab-IAD"}}}}'

![image](https://user-images.githubusercontent.com/39419955/149822516-98519cb6-68e7-47be-bacf-d9be9fd73351.png)

**Comment by spilin** [comment]
@noobtgb It looks like it was a temporary issue. Can you confirm if it is resolved now?

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
