### ISSUE TITLE
BUFFER_OVERRUN Error on mainnet

### ISSUE THREAD

**Issue by end0cr1ne** [aurora-is-near/aurora-relayer#165]
"[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - data out-of-bounds (length=15, offset=32, code=BUFFER_OVERRUN, version=abi/5.5.0). Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"relayer002.backend.internal.aurora.dev","cf-ray":"6cfa42a624bf856c-BOM"}}}}'"

**Comment by mfornet** [comment]
@end0cr1ne do you have the payload, or can describe your interaction with the RPC?

**Comment by mfornet** [comment]
Looking at this similar issue https://github.com/ethers-io/ethers.js/issues/891, it seems to me that the problem might be (here)[https://github.com/aurora-is-near/aurora-relayer/blob/master/src/utils.ts#L82].

**Comment by end0cr1ne** [comment]
TX: https://explorer.mainnet.aurora.dev/tx/0x9e08ac7e9bf9f369d5bf9e1ee5b80409cf7b1921b5459ee825dcd4e277e4610a/internal-transactions

Started happening pretty randomly

**Comment by end0cr1ne** [comment]
> Looking at this similar issue [ethers-io/ethers.js#891](https://github.com/ethers-io/ethers.js/issues/891), it seems to me that the problem might be [here](https://github.com/aurora-is-near/aurora-relayer/blob/master/src/utils.ts#L82).

That seems to be limited to: external's bytes data is not right-padded due to a bug reported in ethereum/solidity#3493. The fix shipped with solc 0.5.x.

My contract uses 0.8.x

**Comment by 0x3bfc** [comment]
@end0cr1ne Can you share the steps to reproduce this issue ? We already had internal discussion and wanted to check whether what I thought is aligned with this issue.

**Comment by mfornet** [comment]
Reopening, as #171 is not confirmed to solve this issue

**Comment by end0cr1ne** [comment]
Hi, To recreate this issue in the truffle console try:
let farm = await Farmv2.at('0xFe427EcbD4FAb2B89b25418364cBF8b454019713')
[FarmV2_abi.txt](https://github.com/aurora-is-near/aurora-relayer/files/7927677/FarmV2_abi.txt)
farm.createFarm(0)
farm.levelUp()

ABI is attached :)

**Comment by end0cr1ne** [comment]
You could also use the frontend: [Link](https://moonflowerfarmers.com/)
Just create a farm(If you can, It's free). Then try to save it. You can see the error in the browser console.

**Comment by end0cr1ne** [comment]
Hey guys, just checking in! Is there anything I can do to help debug this issue?

**Comment by end0cr1ne** [comment]
The error seems to have changed to: "{"value":{"code":-32603,"data":{"code":3,"message":"execution reverted","data":"0x4e487b710000000000000000000000000000000000000000000000000000000000000011"}}}"

**Comment by mfornet** [comment]
@end0cr1ne this is the more informative error we are using after #171. It seems to me like a regular revert operation on the engine, as in, something going wrong with your contract, or the engine itself.

**Comment by end0cr1ne** [comment]
Thanks, @mfornet for all the help, turned out to be a uint being set to a negative value that triggered the revert.
