### ISSUE TITLE
Mainnet is inaccessible

### ISSUE THREAD

**Issue by end0cr1ne** [aurora-is-near/aurora-relayer#168]
The relayer seems to have gone offline. Not sure, can't make any transactions.

**Comment by end0cr1ne** [comment]
Oddly enough it seems to work on some internet providers, not sure what the issue is

**Comment by JonathanLogan** [comment]
This is for a self-hosted relayer or the public infra at https://mainnet.aurora.dev
If the latter: What kind of transaction did you want to make? You might have fallen victim of anti-abuse measures.

**Comment by end0cr1ne** [comment]
What kind of transaction did you want to make? You might have fallen victim to anti-abuse measures.
Definitely did :( I was able to reach out to the team and get an API key.
