### ISSUE TITLE
Reject transactions with insufficient gas

### ISSUE THREAD

**Issue by artob** [aurora-is-near/aurora-relayer#17]
Emulate what happens when trying to send a Ropsten transaction with a gas limit of zero:

```json
{"code": -32000, "message": "intrinsic gas too low"}
```

Related:
- #16
- https://github.com/aurora-is-near/aurora-engine/issues/119

**Comment by 0x3bfc** [comment]
Would like to help in this.

**Comment by 0x3bfc** [comment]
@artob I experienced this error when I used with a gasLimit 20k. So I can confirm that it works.
