### ISSUE TITLE
Cann't connect to mainnet

### ISSUE THREAD

**Issue by AnFuses** [aurora-is-near/aurora-relayer#173]
1. i run a mainnet nearcore successfully
2. i download https://github.com/aurora-is-near/aurora-relayer and run NEAR_ENV=localnet docker-compose up 
3.  i run `http post http://localhost:8545/ jsonrpc=2.0 id=1 method=eth_blockNumber params:='[]'` always got 0x4c00acf, looks like testnet blockNumber

my localnet.yaml: 
\---
port: 8545
database: postgres://aurora:aurora@database/aurora
network: mainnet
endpoint: http://host.docker.internal:3030
engine: aurora
signer: relay.aurora
signerKey:
writable: true

i really confused

**Comment by spilin** [comment]
@AnFuses  Looks like you are running nearcore for testnet. Please check if this assumption is correct.
Also there is a more convenient way to run near core with aurora relayer. Please checkout https://github.com/aurora-is-near/partner-relayer-deploy

**Comment by AnFuses** [comment]
> 

    "chain_id": "mainnet",
    "latest_protocol_version": 50,
    "protocol_version": 50,
    "rpc_addr": "0.0.0.0:3030",
    "sync_info": {
        "earliest_block_hash": "AEmzzoE7LwvQJJH8fYTZ5MN5uZHLUDaYQEzAScDYgAY7",
        "earliest_block_height": 58274974,
        "earliest_block_time": "2022-01-27T20:43:23.875636606Z",
        "latest_block_hash": "GXLFZY2DHB7BAebgAor5F96AXRE6L1iJLUkRqxFkn159",
        "latest_block_height": 58498019,
        "latest_block_time": "2022-01-31T01:28:44.321516672Z",
        "latest_state_root": "9YsLvNKDRzodsZtdiKrhsLNy9bWB8E2AKFQUWigKcbNW",
        "syncing": false
    },

this is the answer by `http get http://localhost:3030/status`. looks like mainnet

i try run  https://github.com/aurora-is-near/partner-relayer-deploy, but cannot connect to it.

**Comment by spilin** [comment]
Can you please provide a bit more details. How are you trying to connect to it, is there any error logs.

**Comment by JonathanLogan** [comment]
Please check the repository readme for RPC endpoint address.
