### ISSUE TITLE
Internal Error - Unknown encoding: 16

### ISSUE THREAD

**Issue by 0x2447196** [aurora-is-near/aurora-relayer#177]
I'm trying to run a simple example program using  [gakonst/ethers-rs](https://github.com/gakonst/ethers-rs) but it seems to fail with the following error message:

```
Error: (code: -32603, message: Internal Error - Unknown encoding: 16. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>, data: Some(Object({"cf-ray": String("6d968b7d12f73fd2-YYZ"), "host": String("relayer008.west.us.backend.internal.aurora.dev")})))
```

this is the Rust program:

```rust
use ethers::prelude::Provider;
use ethers::prelude::*;
use ethers::providers::Middleware;
use ethers::providers::Ws;
use std::time::Duration;
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let ws = Ws::connect("wss://mainnet.aurora.dev").await?;
    let provider = Provider::new(ws).interval(Duration::from_millis(2000));
    let mut stream = provider.watch_blocks().await?.take(5);
    while let Some(block) = stream.next().await {
        dbg!(block);
    }

    Ok(())
}
```

This same program works if I change the endpoint to be any other EVM rpc.

Any idea what's happening? Thanks!.

**Comment by duongthienduc** [comment]
I am having the similar issue when called the `eth_newBlockFilter` method. 
Calling the method using the following cUrl code

`
curl https://testnet.aurora.dev/ -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":1313161555}'
`

will return an error likes this
`{"jsonrpc":"2.0","id":1313161555,"error":{"code":-32603,"message":"Internal Error - Unknown encoding: 16. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6fe6738514018b4d-SEA","request_body":{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":[],"id":1313161555}}}}`

**Comment by spilin** [comment]
Hi @0x2447196. We released a fix. Please check if it helped.

**Comment by zakerikk** [comment]
Hi @0x2447196, this should be resolved by now, please reopen if this issue will reoccur again.
