### ISSUE TITLE
Error: The account aurora wouldn't have enough balance to cover storage

### ISSUE THREAD

**Issue by Jackie-Zhong** [aurora-is-near/aurora-relayer#180]
when i try to deploy contract on aurora testnet with remix,that the error appear like this.

errored: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: The account aurora wouldn't have enough balance to cover storage, required to have 106306749160297968038883 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6db9ea1fc4eb3d12-PDX"}}}}'

**Comment by think-in-universe** [comment]
I have sent 200 NEAR to https://explorer.testnet.near.org/accounts/aurora, so the problem should be resolved. 

However, it would be good that we send a significant amount of NEAR to `aurora` to ensure the Aurora testnet is working well.

**Comment by Jackie-Zhong** [comment]
> I have sent 200 NEAR to https://explorer.testnet.near.org/accounts/aurora, so the problem should be resolved.
> 
> However, it would be good that we send a significant amount of NEAR to `aurora` to ensure the Aurora testnet is working well.

thanks alot,guy!

**Comment by Jackie-Zhong** [comment]
send a significant amount of NEAR to aurora to ensure the Aurora testnet is working well

**Comment by AjyKu** [comment]
> I have sent 200 NEAR to https://explorer.testnet.near.org/accounts/aurora, so the problem should be resolved.
> 
> However, it would be good that we send a significant amount of NEAR to `aurora` to ensure the Aurora testnet is working well.

How did you sent Near to Aurora? I am getting the same error

**Comment by JonathanLogan** [comment]
Has been fixed.
