### ISSUE TITLE
RPC not working

### ISSUE THREAD

**Issue by mcf-rocks** [aurora-is-near/aurora-relayer#182]
According to the documentation the node implements this web3 RPC method, perhaps I do it wrong?
https://doc.aurora.dev/compat/rpc
```
# curl http://172.18.0.4:3030 -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","method": "eth_blockNumber","params": [],"id": 1}'
{"jsonrpc":"2.0","error":{"name":"REQUEST_VALIDATION_ERROR","cause":{"name":"METHOD_NOT_FOUND","info":{"method_name":"eth_blockNumber"}},"code":-32601,"message":"Method not found","data":"eth_blockNumber"},"id":1}root@midget:~# 
```

**Comment by JonathanLogan** [comment]
That was based on an error in the documentation. The URL should be found with:
`$ docker inspect -f '{{range.NetworkSettings.Networks}}http://{{.IPAddress}}:8545{{end}}' endpoint`
