### ISSUE TITLE
ProviderError: Internal Error - Error: The account wouldn't have enough balance to cover storage

### ISSUE THREAD

**Issue by AjyKu** [aurora-is-near/aurora-relayer#183]
Getting below error while deploying contracts to Aurora Testnet. It was working fine 1 hour ago.

ProviderError: Internal Error - Error: The account wouldn't have enough balance to cover storage, required to have 78568527254484941162 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

**Comment by JonathanLogan** [comment]
Has been fixed
