### ISSUE TITLE
Swap failed: ethjs-query while formatting outputs from RPC (TriSolaris + AuroraSwap) r005.eastcoast.us.relayer.internal.aurora.dev

### ISSUE THREAD

**Issue by diazMelgarejo** [aurora-is-near/aurora-relayer#184]
1) on https://www.trisolaris.io/#/swap:
`Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - BadGatewayError. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r005.eastcoast.us.relayer.internal.aurora.dev","cf-ray":"6ddb491256f18b7b-IAD"}}}}'`

2) on https://swap.auroraswap.net/#/swap
`Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":3,"message":"AuroraRouter: INSUFFICIENT_OUTPUT_AMOUNT","data":{"host":"r005.eastcoast.us.relayer.internal.aurora.dev","cf-ray":"6ddb3e96a07b8b7b-IAD"}}}}'`

**Comment by joshuajbouw** [comment]
I'll look into both of these. The 2nd might be related to the contract itself.

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
