### ISSUE TITLE
INFO Trying again after blcok polling failed:Block data unavailable,block was likely unceld(blcok hash = )

### ISSUE THREAD

**Issue by Jackie-Zhong** [aurora-is-near/aurora-relayer#186]
![ofM2nY9Eaf](https://user-images.githubusercontent.com/39180014/154656976-3408fd87-71da-40f3-9275-e3582a5fc191.png)

When I sync the aurora node of test network or main netwoerk on graph-node, it always come to the problem like the screen pic. It looks like it is polling too fast.

**Comment by spilin** [comment]
@Jackie-Zhong  This should be resolved by now, please reopen if this issue will reoccur again.
