### ISSUE TITLE
Error deploying contracts that use library

### ISSUE THREAD

**Issue by Agin-DropDisco** [aurora-is-near/aurora-relayer#188]
{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 83094983 \n Cause: Unknown

contract code : https://github.com/Agin-DropDisco/Aurora/blob/main/ZooHarmony.sol

**Comment by Agin-DropDisco** [comment]
https://explorer.testnet.aurora.dev/tx/0xd714cfe0a628a391de8b719f33c339343255399963c9c98bc2919bfc624332d7/internal-transactions

**Comment by spilin** [comment]
Hi, @rarareceh . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
