### ISSUE TITLE
32603

### ISSUE THREAD

**Issue by Errorister** [aurora-is-near/aurora-relayer#192]
![AURORA BUG](https://user-images.githubusercontent.com/100330153/155449999-6710404b-ba61-414e-bfb3-03091807e5fc.JPG)

**Comment by spilin** [comment]
Hi, @Errorister  . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
