### ISSUE TITLE
the rpc of send raw transaction will block until the tx being packed instead of return immediatly

### ISSUE THREAD

**Issue by DebugFuture** [aurora-is-near/aurora-relayer#193]
The rpc of send raw transaction will block until the tx being packed instead of return immediatly. This is not compatible with eth rpc behavior. 

There are two method in near, broadcast_tx_commit and broadcast_tx_async. I think for the rpc which aurora-relayer provides should use broadcast_tx_async. But now it uses broadcast_tx_commit depending on its dependent libs.

**Comment by spilin** [comment]
You are correct in your assumption. We have plans to work on 'broadcast_tx_async' functionality in the near future.

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
