### ISSUE TITLE
 just got this issue code:32603

### ISSUE THREAD

**Issue by okmsabd** [aurora-is-near/aurora-relayer#194]
cant swap tokens
code: 3260
![sss](https://user-images.githubusercontent.com/100363472/155544612-fefcf527-ed62-4c44-92c5-8044ed08482e.PNG)
3

**Comment by spilin** [comment]
Hi, @okmsabd  . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
