### ISSUE TITLE
testnet aries bug 

### ISSUE THREAD

**Issue by erolmusti** [aurora-is-near/aurora-relayer#195]
Hi, 
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.eastcoast.us.testnet.internal.aurora.dev","cf-ray":"6e2bf30a33ce5c56-IAD"}}}}'

My metamask adress: 0x0d2Bcd389EeF1465631A242759380B06549b8AB7

**Comment by spilin** [comment]
Hi, @erolmusti . This should be resolved.
