### ISSUE TITLE
Testnet aries swap fail

### ISSUE THREAD

**Issue by DontFoldBB** [aurora-is-near/aurora-relayer#196]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 83898338 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e4bae3644367b83-DME"}}}}'

**Comment by spilin** [comment]
Hi, @DontFoldBB . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
