### ISSUE TITLE
maybe bug ?

### ISSUE THREAD

**Issue by xicorcrypto** [aurora-is-near/aurora-relayer#198]
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84001681 \n Cause: Unknown.

{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e56aa852766897c-IAD"}}}}

**Comment by spilin** [comment]
Hi, @xicorcrypto  . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
