### ISSUE TITLE
aries dex testnet bug

### ISSUE THREAD

**Issue by sheisdarya** [aurora-is-near/aurora-relayer#199]
while swapping eth to ausd keep getting this bug:

Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84026313 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e59882233e998a2-SEA"}}}}'

**Comment by spilin** [comment]
Hi, @sheisdarya  . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
