### ISSUE TITLE
32603- Borrow transaction Failed

### ISSUE THREAD

**Issue by ahmkah** [aurora-is-near/aurora-relayer#202]
[](url
![bug-2](https://user-images.githubusercontent.com/99053148/156458048-ff2961b7-7ebc-4198-8279-4c09b6b97447.JPG)
)

**Comment by Alfexclancy** [comment]
The abow error messege I received while borrowing
603: Internal Error - Error: The account aurora wouldn't have enough balance to cover storage, required to have 181361104920912403006 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

**Comment by zakerikk** [comment]
Hi @Alfexclancy, can you try again?

**Comment by luffyvnx** [comment]
The same issues for me,
Internal Error - Error: The account  wouldn't have enough balance to cover storage, required to have 10071859503678743274908 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

**Comment by spilin** [comment]
Hi @luffyvnx , @Alfexclancy. Are you still encountering this issue?
