### ISSUE TITLE
repay

### ISSUE THREAD

**Issue by mrthkm** [aurora-is-near/aurora-relayer#205]
Repay Transaction Failed!
-32603: Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84174912 Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>
wallet address : 0x8B139211fD5f39C9f4943D0C2039957E8609e960

**Comment by spilin** [comment]
Hi, @mrthkm . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
