### ISSUE TITLE
Withdrawing issues

### ISSUE THREAD

**Issue by Tsykatunov** [aurora-is-near/aurora-relayer#206]
Don’t know much of the code which is written so I’ll just leave that to you here. Was trying to withdraw that supply of USDC at testnet and got this errors.

<img width="320" alt="Screenshot 2022-03-04 at 14 28 55" src="https://user-images.githubusercontent.com/88035198/156755776-4b3de590-e603-421d-8390-accd805084ad.png”>

<img width="322" alt="Screenshot 2022-03-04 at 14 24 21" src="https://user-images.githubusercontent.com/88035198/156755823-c0de3524-2b21-4e8b-ac00-07ea5fee630d.png">

**Comment by spilin** [comment]
This issue should be resolved.
