### ISSUE TITLE
transaction error 

### ISSUE THREAD

**Issue by aliffianto** [aurora-is-near/aurora-relayer#209]
i can to borrow and i think my stROSE balance is enought to transaction but if i transaction for borrow my stROSE in my wallet i get to message :  

Borrow Transaction Failed!
-32603: BoringERC20: TransferFrom failed

**Comment by spilin** [comment]
Is this is still relevant? Can you please provide more info. Full error log, screenshot, etc..

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
