### ISSUE TITLE
Transactionfiled

### ISSUE THREAD

**Issue by Yayatbusiat** [aurora-is-near/aurora-relayer#211]
Repay Transaction Failed!
-32603: BoringERC20: TransferFrom failed

0x5512bA9b269B48676Ab09F22E307CD5F4F4C2184

**Comment by mfornet** [comment]
Please provide more information! What is the error message from the tool you are using? Which network are you using? Which app are you using?

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
