### ISSUE TITLE
http://testnet.rose.fi/#/borrow/near

### ISSUE THREAD

**Issue by mohamed10ayoub** [aurora-is-near/aurora-relayer#213]
-32603: Internal Error - FetchError: invalid json response body at http://192.168.1.89:3030/ reason: Unexpected end of JSON input. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

**Comment by mfornet** [comment]
Hey, this seems to be a problem with the application you are using and not with the public RPC. Please get in touch with them. Feel free to reopen the issue with more info if you think the problem is with the public RPC.
