### ISSUE TITLE
swap  aex-meme

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#215]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - BadGatewayError. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7cda0e425d16ec-IAD"}}}}'

**Comment by mfornet** [comment]
Same as #216

Please don't open the same issue several times.
