### ISSUE TITLE
Internal Error - BadGatewayError

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#216]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - BadGatewayError. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7ce15831243a55-IAD"}}}}'

**Comment by mfornet** [comment]
Testnet is under heavy load, more than what the public RPC can handle at the moment. Can you retry and see if this is still a problem? 

We are working on a more reliable solution to this issues.
