### ISSUE TITLE
Swap failed aex-eth

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#217]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - . Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7ce5f644be7b87-DME"}}}}'

**Comment by mfornet** [comment]
Can you describe which tx were you doing that triggered this issue?

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
