### ISSUE TITLE
ERR_INCORRECT_NONCE

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#218]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"ERR_INCORRECT_NONCE","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7ce86921847b43-DME"}}}}'

**Comment by mfornet** [comment]
The transaction was using an old or invalid nonce.

This usually happens when you send several txs from the same address too fast. Either you make a timeout between transactions, or you handle nonces manually and appropiately.
