### ISSUE TITLE
Swap failed weth-aex

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#219]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r003.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7d04bf271c1654-DME"}}}}'

**Comment by mfornet** [comment]
same as #226
