### ISSUE TITLE
Borrow Transaction Failed! atUST

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#222]
Borrow Transaction Failed! -32603: Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84358518 Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

![image](https://user-images.githubusercontent.com/95912427/156939185-3c43c282-3e20-4ca4-a136-9bf8c3748fdf.png)

**Comment by mfornet** [comment]
Same as #223
