### ISSUE TITLE
DB Not Found Error: BLOCK HEIGHT

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#223]
Repay Transaction Failed!
-32603: Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84358741 Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

![image](https://user-images.githubusercontent.com/95912427/156939291-72524a57-2e2f-4566-a5ce-3aab67f983cd.png)

**Comment by mfornet** [comment]
If you retry this error should not appear again.

We are working in a more robust fix for this problem, that should land in ~two of weeks.

**Comment by mfornet** [comment]
@spilin we are hitting this error to frequently by the number of reports we have. Is there anyway we can deal with that by checking previous existing block for the moment?

**Comment by spilin** [comment]
This issue should be resolved. Please reopen if it reoccurs.
