### ISSUE TITLE
Repay Transaction Failed! -32603: BoringERC20: TransferFrom failed

### ISSUE THREAD

**Issue by uudsahid** [aurora-is-near/aurora-relayer#225]
Repay Transaction Failed! -32603: BoringERC20: TransferFrom failed
![repay](https://user-images.githubusercontent.com/72332460/156940899-c73ea8a3-c64d-4314-bd8c-69f59181ff6a.jpg)

**Comment by uudsahid** [comment]
I try More than 10 times.. its same,, Not work stil not fixed

**Comment by mfornet** [comment]
Hi @uudsahid it would be great if you could copy past the content of the error here. 

There is a high chance it is related to #229 In which case it should be solved already.

**Comment by wisp777** [comment]
Hello. There was an error, but the second time the error was gone. (0xABeAC81D754533533ab7B2CD9aC3Fa67711b0f74)
![r2](https://user-images.githubusercontent.com/97223525/160241310-d7fe24a3-916f-476b-84a2-7253d0e25454.png)

**Comment by spilin** [comment]
Hello, @uudsahid. There is a fix landed on testnet that should resolve `DB Not Found Error`.Can you please validate if this still reproducable. Thank you in advance

**Comment by spilin** [comment]
This issue should be resolved. Please reopen if it reoccurs.
