### ISSUE TITLE
Swap failed when try to swap MEME to ETH

### ISSUE THREAD

**Issue by VikomiC** [aurora-is-near/aurora-relayer#227]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: The account wouldn't have enough balance to cover storage, required to have 96166939801195556350316 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.eastcoast.us.testnet.internal.aurora.dev","cf-ray":"6e7e43ae4363b49c-IAD"}}}}'

![image](https://user-images.githubusercontent.com/9350353/156943379-fa4b5fa6-f30e-4e80-9eab-09fe91a23480.png)

**Comment by VikomiC** [comment]
Same for swap MEME to WETH

**Comment by mfornet** [comment]
It should work right now.

Long answer on https://github.com/aurora-is-near/aurora-relayer/issues/229#issuecomment-1061655391
