### ISSUE TITLE
faucet failed all tokens 

### ISSUE THREAD

**Issue by fahad143** [aurora-is-near/aurora-relayer#228]
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: The account wouldn't have enough balance to cover storage, required to have 576855400506225610792 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r003.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e813ca615b63bf5-IAD"}}}}'

**Comment by mfornet** [comment]
It should work right now.

Long answer on https://github.com/aurora-is-near/aurora-relayer/issues/229#issuecomment-1061655391
