### ISSUE TITLE
Internal JSON-RPC error

### ISSUE THREAD

**Issue by chidoman321** [aurora-is-near/aurora-relayer#23]
i've deployed an erc721 in the aurora testnet , and i retrieve tokens in a page, so when i mint a new one this error apppears on that page, and then after a while it is working again 

this is the smart contract that i am using 
https://github.com/cristian-cloudmex/NFT-culturas-latinas/blob/master/blockchain/contracts/MarketPlace.sol

the method that i call is obtenerNftsEnVenta()

Uncaught (in promise) Error: Internal JSON-RPC error.
{
  "code": -32603,
  "message": "Internal error, please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>",
  "data": {
    "host": "testnet.aurora.dev",
    "cf-ray": "6682700b1711091f-ATL"
  }
}

**Comment by 0x3bfc** [comment]
@chidoman321 I don't have access to the UI for your application but it works if I use Truffle as shown below: 

```
ahmedali@Ahmeds-MBP blockchain % truffle console --network aurora
truffle(aurora)> const marketplace = await MarketPlace.deployed()
undefined
truffle(aurora)> await marketplace.minero()
'0x6A33382de9f73B846878a57500d055B981229ac4'
truffle(aurora)> await marketplace.minar("0xe364C743d4C6DAF40bd08073E8fb4B2AD54e7811", "my first nft", 23)
{
  tx: '0x4914b6bb1c80d84726cec866abc1ed3f0c8b406782f22d91541930384c7772ea',
  receipt: {
    blockNumber: 54153179,
    blockHash: '0xdb6bec7309b739824636f455fd1ce0d699e885c4533b7b93ec7cf5d2c43aebac',
    transactionIndex: 0,
    transactionHash: '0x4914b6bb1c80d84726cec866abc1ed3f0c8b406782f22d91541930384c7772ea',
    from: '0x6a33382de9f73b846878a57500d055b981229ac4',
    to: '0x65964fe8eb8124c3ec6417bfd5e8733ddedb92d7',
    gasUsed: 180204,
    cumulativeGasUsed: 0,
    contractAddress: null,
    logs: [ [Object] ],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: true,
    nearTransactionHash: '0xea9643620951db2a061c74ef424565e97a102a059f0b41b9818f912d781aedbd',
    nearReceiptHash: '0x33eb1134940812481d87f6d59e01a1cdc696a54bc66040826573134b3186aaff',
    rawLogs: [ [Object] ]
  },
  logs: [
    {
      blockNumber: 54153179,
      blockHash: '0xdb6bec7309b739824636f455fd1ce0d699e885c4533b7b93ec7cf5d2c43aebac',
      transactionIndex: 0,
      transactionHash: '0x4914b6bb1c80d84726cec866abc1ed3f0c8b406782f22d91541930384c7772ea',
      logIndex: 0,
      address: '0x65964fe8EB8124C3Ec6417BFD5e8733dDEDb92d7',
      removed: false,
      id: 'log_ed4dc428',
      event: 'Transfer',
      args: [Result]
    }
  ]
}
```

**Comment by paouvrard** [comment]
This error 32603 previously happened a couple times randomly, but right now happens on every Metamask transaction on testnet.
cc @artob @0x3bfc 
![image](https://user-images.githubusercontent.com/29397451/125580141-f93c0218-a392-4022-91d1-198660a1bd17.png)

**Comment by birchmd** [comment]
This is maybe related to the recent NEAR testnet outage? I think maybe the times coincide. If so then maybe our relayers need better error handling to pass this down to metamask in some graceful way?

**Comment by paouvrard** [comment]
Right, now it is back to how it was before and only occurs occasionally.

**Comment by 0x3bfc** [comment]
I'll work on it

**Comment by 0x3bfc** [comment]
@chidoman321 I have used your [marketplace app](https://github.com/cristian-cloudmex/NFT-culturas-latinas/) and It seems to be working with your DApp
![image](https://user-images.githubusercontent.com/5428661/126745300-c91a151f-d5c9-4871-8b36-183aed72945b.png)
![image (3)](https://user-images.githubusercontent.com/5428661/126745316-c2c849a6-049e-40ab-879c-437f4d926718.png)
![image (2)](https://user-images.githubusercontent.com/5428661/126745326-88dcdf1a-3afe-4a31-b5da-53cc0c19f88d.png)

**Comment by chidoman321** [comment]
hi @0x3bfc  the problem is located in the galeria view , you should change the tokensperpage value to a number greater than seven  
![image](https://user-images.githubusercontent.com/49621062/126814339-1c129f57-c6b6-41b2-90b5-974436af2575.png)

**Comment by chidoman321** [comment]
https://develop-latinart.netlify.app/

**Comment by 0x3bfc** [comment]
@chidoman321 @paouvrard After investigating the issue, it seems to be a gas limit issue
```
testnet_endpoint | {"level":50,"time":1627378107614,"pid":7,"hostname":"db668df5ccda","type":"UntypedError","stack":"Error: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded)).\n{\n  \"block_hash\": \"D9PQ6WRKqZwvrsvdYF9kgM6jV6w3266vX6p16TxifcaD\",\n  \"block_height\": 56760561,\n  \"error\": \"wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded))\",\n  \"logs\": []\n}\n    at JsonRpcProvider.query (/srv/aurora/relayer/node_modules/near-api-js/lib/providers/json-rpc-provider.js:80:19)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)\n    at async Engine.callFunction (file:///srv/aurora/relayer/node_modules/@aurora-is-near/engine/lib/engine.js:243:24)\n    at async Engine.view (file:///srv/aurora/relayer/node_modules/@aurora-is-near/engine/lib/engine.js:183:16)\n    at async DatabaseServer.eth_call (file:///srv/aurora/relayer/lib/servers/database.js:67:17)","msg":"Querying [object Object] failed: wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded)).\n{\n  \"block_hash\": \"D9PQ6WRKqZwvrsvdYF9kgM6jV6w3266vX6p16TxifcaD\",\n  \"block_height\": 56760561,\n  \"error\": \"wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded))\",\n  \"logs\": []\n}"}

```

**Comment by cozmbatman** [comment]
I am running into same issue right now and its happening consistently.
When i try to deploy a smart contract via remix, i get this issue, but if i switch the Javascript VM to London or Berlin version in remix, i am able to successfully deploy the contract.

Same thing happens when i try to call the deployed contract methods via Metamask or use Web3 library in nodejs.
I am trying to connect to `testnet` right now.

**Comment by 0x3bfc** [comment]
we are aware of this issue, and working on it ...... it should be fixed very soon.

**Comment by 0x3bfc** [comment]
blocked by https://github.com/aurora-is-near/aurora-engine/pull/249 and https://github.com/aurora-is-near/aurora-engine/issues/199

**Comment by 0x3bfc** [comment]
> I am running into same issue right now and its happening consistently.
> When i try to deploy a smart contract via remix, i get this issue, but if i switch the Javascript VM to London or Berlin version in remix, i am able to successfully deploy the contract.
> 
> Same thing happens when i try to call the deployed contract methods via Metamask or use Web3 library in nodejs.
> I am trying to connect to `testnet` right now.
> 
> Also i tried the @chidoman321 [marketplace](https://github.com/cristian-cloudmex/NFT-culturas-latinas/) and see the same exception in console there when trying to pay with metamask

Can you try again ?

**Comment by 0x3bfc** [comment]
closing this issue as I didn't hear back from @chidoman321 . Feel free to reopen it, if you still has this issue.
