### ISSUE TITLE
The same code can be deployed on the main network, but not the test network

### ISSUE THREAD

**Issue by zhonggc** [aurora-is-near/aurora-relayer#231]
2022/03/09, I deployed a standard ERC20 contract on the test network successfully, but it has failed since 2022/03/09. The following error message is displayed:
creation of ERC20 errored: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: The account  wouldn't have enough balance to cover storage, required to have 10083980782236379657040 yoctoNEAR more. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6e920421d27a3c3a-PDX"}}}}'

**Comment by zhonggc** [comment]
I recharged WNEAR according to the error information, but it was still the error information. And I don't understand why it's about Near. although

**Comment by zhonggc** [comment]
I have enough ETH in my account, but still not enough
![image](https://user-images.githubusercontent.com/30102427/157394154-314cd252-039c-48dd-b181-7420e8f89d4d.png)

**Comment by niccolopetti** [comment]
I'm facing the same issue

**Comment by AymericNoel** [comment]
Same here

**Comment by birchmd** [comment]
Hi all,

Sorry for the inconvenience. This error "The account wouldn't have enough balance to cover storage" is referring to the Aurora Engine's account on the NEAR testnet. NEAR has a "storage staking" concept (you can read more about this [here](https://docs.near.org/docs/concepts/storage-staking)) which means our Engine account on NEAR needs to hold more and more NEAR base token as the state it uses grows (and I has grown a lot lately!).

Our ops team works to stay on top of providing more NEAR to the account on a regular basis, but the rate of growth of the state together with the ongoing Ukraine crisis means sometimes we fall behind. More NEAR has been added to the account so hopefully you will not encounter this issue now.

Please feel free to re-open this ticket if the issue returns and we can add more NEAR to the Engine's account.

**Comment by AymericNoel** [comment]
Thanks !

**Comment by zhonggc** [comment]
No worry, thanks !
