### ISSUE TITLE
Metamask could not switch to the auraro testnet

### ISSUE THREAD

**Issue by zhonggc** [aurora-is-near/aurora-relayer#232]
![image](https://user-images.githubusercontent.com/30102427/157603943-9dd14f15-fb4a-4075-a399-f3dd5c9571ec.png)
![image](https://user-images.githubusercontent.com/30102427/157604187-a56460c0-6644-4c71-92af-588cf8c22803.png)

**Comment by mfornet** [comment]
I tried both with aurora `testnet` and `mainnet` and it is working. Probably this happened because the endpoint was slow to respond or inaccessible to you (in which case I may suggest you try using a VPN). Please reopen if you still see the issue consistently to debug on our end.

**Comment by zhonggc** [comment]
thanks!
