### ISSUE TITLE
Swap failed AUSD-MEME

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#235]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84747894 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6ea6487e37f800b8-IAD"}},"stack":"{\n \"code\": -32603,\n \"message\": \"Internal JSON-RPC error.\",\n \"data\": {\n \"code\": -32603,\n \"message\": \"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 84747894 \\n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>\",\n \"data\": {\n \"host\": \"r002.westcoast.us.testnet.internal.aurora.dev\",\n \"cf-ray\": \"6ea6487e37f800b8-IAD\"\n }\n },\n \"stack\": \"Error: Internal JSON-RPC error.\\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:123658)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:121201)\\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:121811)\\n at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:80887)\\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:81919\\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:5803\"\n}\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:123658)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:121201)\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:121811)\n at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:80887)\n at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:81919\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:5803"}}'

![image](https://user-images.githubusercontent.com/95912427/157926713-10c75ca9-c74c-4f43-948b-92ebd2f52d17.png)

**Comment by spilin** [comment]
Hi, @HeiMoli . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
