### ISSUE TITLE
ERROR WHEN REPAY

### ISSUE THREAD

**Issue by TLGKien** [aurora-is-near/aurora-relayer#237]
![Screenshot from 2022-03-12 11-41-33](https://user-images.githubusercontent.com/63689509/158003979-363f543a-5cb0-44bb-b3d7-bac384c75b38.png)
I can not repay, I tried 4,5 times. please fix bugs or explain this reason

**Comment by spilin** [comment]
Hi, @TLGKien. This is unrelated to aurora-relayer, but I will forward it to relevant team.
