### ISSUE TITLE
Error when display

### ISSUE THREAD

**Issue by TLGKien** [aurora-is-near/aurora-relayer#239]
![Screenshot from 2022-03-12 12-00-08](https://user-images.githubusercontent.com/63689509/158004589-45761968-fca6-4435-8c01-f1acdee5e0c5.png)
i input 1000 near, i think it should be ~8000 $, or ~1000 near, not ~8000 near

**Comment by spilin** [comment]
Hi, @TLGKien. This is unrelated to aurora-relayer, but I will forward it to relevant team. In order for that to happened, i would need more details on a service where this occurs. Link or steps would be very helpful.
