### ISSUE TITLE
Swap failed ausd-meme

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#240]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - FetchError: invalid json response body at http://192.168.1.89:3030/ reason: Unexpected end of JSON input. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6eaccd9e40659db4-IAD"}}}}'

![image](https://user-images.githubusercontent.com/95912427/158019502-2a30616f-b7c9-4228-8f1d-bc014b73a744.png)

**Comment by spilin** [comment]
Hello. Is this issue occurs on testnet, mainnet or do you run your own relayer/near infra. Also can you please confirm that was not a temporary issue and is still relevant.

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
