### ISSUE TITLE
502 gateway error

### ISSUE THREAD

**Issue by Oliver-Baekdu** [aurora-is-near/aurora-relayer#241]
Error: Returned error: Internal Error -
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
. Please report a bug at https://github.com/aurora-is-near/aurora-relayer/issues

I got above error when I repeatedly call read function to my own node. when this error happens, this error appears whenever I call any function.

**Comment by spilin** [comment]
Hello. Is this issue occurs on testnet or mainnet. Also can you please confirm that it is not yet resolved.

**Comment by Oliver-Baekdu** [comment]
this issue occurs on mainnet and it is not yet resolved

**Comment by spilin** [comment]
@Oliver-Baekdu Please provide more details. Perhaps you have a script that I can use to reproduce this issue?

**Comment by Oliver-Baekdu** [comment]
my script calls read function three times a second for crawling dex's lp data.

**Comment by spilin** [comment]
@Oliver-Baekdu Should be resolved now.
