### ISSUE TITLE
UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT

### ISSUE THREAD

**Issue by HeiMoli** [aurora-is-near/aurora-relayer#243]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":3,"message":"UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT","data":{"host":"r001.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6ec94694658f502b-SEA"}}}}'
![image](https://user-images.githubusercontent.com/95912427/158492446-74cd4bd7-7028-4169-b72c-1c1d51bdeaba.png)

**Comment by mfornet** [comment]
This is not an error coming from the relayer, but an error with the app you are using. Please open an issue with them.
In particular this error is with the contract: `UniswapV2Router` that they are using.
