### ISSUE TITLE
Transactions need to be sorted sequentially

### ISSUE THREAD

**Issue by joshuajbouw** [aurora-is-near/aurora-relayer#247]
Some users submit multiple transactions in a single block that needs to be batched. Currently, if a user submits multiple transactions at one time, there is no guarantee that it'll execute sequentially as per the nonce value causing `ERR_INCORRECT_NONCE` issues.

Related: https://github.com/aurora-is-near/aurora-engine/issues/451

**Comment by waldmatias** [comment]
Hello! I'm just wondering if there is any progress on this issue? seems a few people are hitting this error as of today. @joshuajbouw thanks!

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
