### ISSUE TITLE
Execution Reverted

### ISSUE THREAD

**Issue by mfornet** [aurora-is-near/aurora-relayer#248]
One partner is having this issue consistently in the last few days while using the public RPC.

```
{
    "code": -32603,
    "message": 
    "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x\"}}}'"
}
```

**Comment by spilin** [comment]
@mfornet Are there any additional info? Maybe script that I can use to reproduce this?

**Comment by mfornet** [comment]
It happens from time to time on saving actions on https://moonflowerfarmers.com/.

**Comment by end0cr1ne** [comment]
To replicate use:
Create a farm here: 
https://moonflowerfarmers.com/

ABI: [Uploading FarmV5.txt…]()
Hosted at: 0xDE707357D10D86aE21373b290eAbBA07360896F6
call the sync public function with this payload:
[
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 1,
        "createdAt": 1647615841
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 2,
        "createdAt": 1647615842
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 3,
        "createdAt": 1647615843
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 1,
        "createdAt": 1647615919
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 2,
        "createdAt": 1647615920
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 3,
        "createdAt": 1647615921
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 1,
        "createdAt": 1647615923
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 2,
        "createdAt": 1647615923
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 3,
        "createdAt": 1647615924
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 0,
        "createdAt": 1647615926
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 4,
        "createdAt": 1647615927
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 0,
        "createdAt": 1647615990
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 2,
        "createdAt": 1647615991
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 4,
        "createdAt": 1647615992
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 3,
        "createdAt": 1647615995
    },
    {
        "action": 1,
        "fruit": "0",
        "landIndex": 1,
        "createdAt": 1647615997
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 0,
        "createdAt": 1647615998
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 2,
        "createdAt": 1647615998
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 3,
        "createdAt": 1647615999
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 4,
        "createdAt": 1647615999
    },
    {
        "action": 0,
        "fruit": "1",
        "landIndex": 1,
        "createdAt": 1647616000
    }
]

**Comment by chad-mcdonald** [comment]
Having the same issue with one of our functions on testnet.  To reproduce:

1. [Contract](https://testnet.aurorascan.dev/address/0xb33662ce7192ea0c4d73448528d3e5ebec85a03b#writeContract)
2. In the claim() function fill in these values:  

- To: 0x237f6EC93A1E68819b24361aBC1e8cf5cA8d9bce 
- Amount: 100000000000000000000 
- Proof: 0xcd537fb58a8b1f066d539bd51ef725bfab2cb0487cbe5f430d1394f3e4a00962

3. Claim and sign the TX with metamask.  Which will return this error:

`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":3,"message":"execution reverted","data":"0x8a585be2"}}}'`

**Comment by end0cr1ne** [comment]
@mfornet Any updates here :)

**Comment by mfornet** [comment]
It seems to me that there is a problem with the contract, and it is being reverted due to some issue inside the logic of the contract. I kind of confirmed this by looking into @chad-mcdonald provided contract, you can see how most of the transactions are failures, and that is not related to the RPC.

However, the RPC should be able to return back a better error message which could be parsed by off-chain tools. This was addressed at https://github.com/aurora-is-near/aurora-relayer/pull/97, but it looks like it wasn't completely addressed at that point. cc @spilin

**Comment by spilin** [comment]
Hey, @mfornet @end0cr1ne . We will investigate it this week. As to returning proper errors, as of now it's not all of the messages can be returned.

**Comment by end0cr1ne** [comment]
The only reason I assumed that it was engine related is that these started last week randomly without any change from my end :(

**Comment by end0cr1ne** [comment]
Hey @spilin did you get a chance to look into this. My app's significantly affected 😔

**Comment by birchmd** [comment]
> The only reason I assumed that it was engine related is that these started last week randomly without any change from my end :(


@end0cr1ne this suddenly started happening on testnet or mainnet? There have been no changes to the Engine on mainnet since Feb 23 (1 month ago).

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
