### ISSUE TITLE
Swap failed AUSD-MEME

### ISSUE THREAD

**Issue by Kylaguzz** [aurora-is-near/aurora-relayer#249]
![swap failed](https://user-images.githubusercontent.com/99951219/159155180-71c3ef87-5869-4f40-b4df-be0c627848f9.png)
![swap failed 2](https://user-images.githubusercontent.com/99951219/159155183-8b6e6c1a-8d6f-4205-8b50-f26bf372c4b0.png)

Conducted swaps, supplied liquidity to pools. Found one issue while swapping AUSD-MEME. Screenshots attached.
Desktop, windows 10, chrome

**Comment by spilin** [comment]
Hi, @Kylaguzz . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
