### ISSUE TITLE
Bug when Swap AEX - MEME

### ISSUE THREAD

**Issue by youvovk** [aurora-is-near/aurora-relayer#250]
Received the following error while exchanging a pair AEX - MEME
The error appeared after the transaction was confirmed. Also the resubmission was successful

`Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 85449745 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r002.westcoast.us.testnet.internal.aurora.dev","cf-ray":"6eeфd86a486aa2473-KBP"}}}}'`

Device - Desktop, macOS, chrome

**Comment by spilin** [comment]
Hi, @youvovk . We are aware of this issue and are working to resolve it. As of now - retrying operation should help.
Same as https://github.com/aurora-is-near/aurora-relayer/issues/223
