### ISSUE TITLE
Different explorers/nodes give different eth_getLogs results

### ISSUE THREAD

**Issue by evmer** [aurora-is-near/aurora-relayer#251]
https://explorer.mainnet.aurora.dev/tx/0xa7e38872448d2681f667d13143f2b771f8ca9aa9e152e8ca9975598ba26079d9/logs
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/10036897/159175681-b3a530ee-cfb5-43a7-85b4-4b13d289bb64.png">

**Here, the first log result gives address "0x2CB45Edb4517d5947aFdE3BEAbF95A582506858B"**

**https://aurorascan.dev/tx/0xa7e38872448d2681f667d13143f2b771f8ca9aa9e152e8ca9975598ba26079d9#eventlog**
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/10036897/159175662-db53982b-7a03-43ff-99a8-5c5001272053.png">

**Different explorer/node, for the first log result of the same tx gives address "0xfa94348467f64d5a457f75f8bc40495d33c65abb"**.

Who is right?

**Comment by spilin** [comment]
@evmer Should be resolved now.
