### ISSUE TITLE
Rose tesnet bug

### ISSUE THREAD

**Issue by Vindicator78** [aurora-is-near/aurora-relayer#252]
Hi. i am finding bug, then used Rose testnet. I wish repay RUSD, but my transaction is failded. Thats brought me here. Leaving screen down here
![Fail Rose testnet](https://user-images.githubusercontent.com/102321952/159988308-e7ec26c1-ae7c-4f74-a15f-477032db8ccd.jpg)
.

**Comment by spilin** [comment]
Hello, @Vindicator78 . There is a fix landed on testnet that should resolve `DB Not Found Error`.Can you please validate if this still an issue. Thank you in advance.

**Comment by Vindicator78** [comment]
Thanks, I'm tested Rose second time. All options (stake, farm, swap, borrow & repay) are working. Transaction speed impruved too. You, guys, did good job!
