### ISSUE TITLE
DB Not found error

### ISSUE THREAD

**Issue by git-ff** [aurora-is-near/aurora-relayer#253]
I faced an issue during the testing Borrow section at testnet.
For test I used the second wallet: 0xa81Bd184eF71b79A81296D38FCFe8f1e44589871

![Screenshot 2022-03-25 at 01 48 12](https://user-images.githubusercontent.com/3162657/160056770-4e754d91-2547-484d-98fd-41c797a12319.png)

**Comment by mfornet** [comment]
Same as #223

**Comment by spilin** [comment]
Hello, @git-ff  . There is a fix landed on testnet that should resolve `DB Not Found Error`.Can you please validate if this still an issue. Thank you in advance.
