### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by johnDoe3212** [aurora-is-near/aurora-relayer#254]
Unknown bug
![msg782888501-198116](https://user-images.githubusercontent.com/99414911/160233683-6031724d-9c0f-4327-b798-582671d3b595.jpg)

**Comment by spilin** [comment]
Hi @johnDoe3212. There is a fix landed on testnet. Can you please try and validate if this issue is still occurring?

**Comment by spilin** [comment]
This issue should be resolved. Please reopen if it will reappear.
