### ISSUE TITLE
Rose Testnet Bug

### ISSUE THREAD

**Issue by kytyi** [aurora-is-near/aurora-relayer#255]
![Uploading Знімок екрана (11).png…]()

Got a bag when try to repay UST

**Comment by spilin** [comment]
Hi, @kytyi.Unfortunatly image is no longer available. If error is related to:
`-32603: Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 86451935 Cause: Unknown. Please report a bug at https://github.com/aurora-is-near/aurora-relayer/issues`, then please try again on testnet. There is a fix landed there and would be great if you could confirm/deny if it resolved this issue.

**Comment by spilin** [comment]
This issue should be resolved. Please reopen if it will reappear.
