### ISSUE TITLE
Rose Testnet Bug when trying to borrow

### ISSUE THREAD

**Issue by ArlinaMaxil** [aurora-is-near/aurora-relayer#256]
<img width="583" alt="Bug" src="https://user-images.githubusercontent.com/102547836/160459875-de962d34-194b-480f-be47-cf54ba153cff.png">

Hi! I have found that bug when trying to borrow RUSD and put NEAR as collateral at the same time in ROSE testnet.

My wallet is 0x09774547500693967d68c6151A7785984e778D6c

**Comment by spilin** [comment]
hi @ArlinaMaxil  . There is a fix landed on testnet. Can you please try and validate if this issue is still occurring?

**Comment by spilin** [comment]
This issue should be resolved.
