### ISSUE TITLE
web3 token claim error

### ISSUE THREAD

**Issue by ars904** [aurora-is-near/aurora-relayer#257]
showing this error when i try to claim Aries Exchange Testnet Token (AEX)

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 86147176 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.eastcoast.us.testnet.internal.aurora.dev","cf-ray":"6f327d0357489776-AMS"}}}}'

**Comment by spilin** [comment]
hi @ars904  . There is a fix landed on testnet. Can you please try and validate if this issue is still occurring?

**Comment by spilin** [comment]
This issue should be resolved.

**Comment by ars904** [comment]
now web3 token claim error  issue  is resolved. thanks

**Comment by ars904** [comment]
> This issue should be resolved.

now web3 token claim error issue is resolved. thanks
