### ISSUE TITLE
aurora testnet / rose testnet 

### ISSUE THREAD

**Issue by mondley** [aurora-is-near/aurora-relayer#259]
-32603: Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 86209346 Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues> 

I participate in the testnet. Knocked out this error

**Comment by mfornet** [comment]
Same as #223

**Comment by mondley** [comment]
Thanks for the answer

вт, 29 мар. 2022 г. в 14:56, Marcelo Fornet ***@***.***>:

**Comment by spilin** [comment]
hey @mondley . Can you please try again. We have a fix landed on testnet and are trying to validate whether it resolved this issue or not. Thank you in advance.

**Comment by mondley** [comment]
It's working.

чт, 7 апр. 2022 г. в 13:47, spilin ***@***.***>:

**Comment by spilin** [comment]
Great to hear, thank you.
