### ISSUE TITLE
Error sending MetaMask transactions on testnet

### ISSUE THREAD

**Issue by paouvrard** [aurora-is-near/aurora-relayer#26]
Getting the following error when sending Aurora testnet transactions from MetaMask (v9.8.4)
```Error: [ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":3,\"message\":\"execution reverted:\",\"data\":\"0x\"}}}'```
But the transaction is correctly executed by `relay.aurora`: https://explorer.testnet.near.org/transactions/BSRVi4JbncuuZuyWPi7riqP8q68oyCvxVDzA5gL2LYzo

**Comment by 0x3bfc** [comment]
@paouvrard Is there a way to reproduce this error message ?

**Comment by paouvrard** [comment]
@0x3bfc This is happening to me on every MetaMask transaction: a regular ETH transfer created in MetaMask could reproduce it.

**Comment by 0x3bfc** [comment]
This issue related to the new updates in the Aurora EVM. Fix will come very soon.
