### ISSUE TITLE
How Can I set Rate Limit???

### ISSUE THREAD

**Issue by godtaehee** [aurora-is-near/aurora-relayer#260]
Thanks for all who contributes this repo.

I can make Aurora-Node with this kindly repository Documentation.

But, As you see in title, How Can I set Rate Limit ?????

I mean that I wanna change request limit for specific my bot.

[This Ethereum Network Set Rate Limit docs in Infura](https://docs.infura.io/infura/networks/ethereum/how-to/secure-a-project/set-rate-limits) will help you to understand what I saying.

Can you help me??

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
