### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dprylypko** [aurora-is-near/aurora-relayer#261]
-32603: Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 86451935 Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

**Comment by spilin** [comment]
hi @dprylypko . There is a fix landed on testnet. Can you please try and validate if this issue is still occuring?

**Comment by dprylypko** [comment]
Hi
Everything working

**Comment by spilin** [comment]
That is great to hear. Thank you. Please feel free to reopen this issue if it will occur again
