### ISSUE TITLE
[BUG] Can not sign transactions for account

### ISSUE THREAD

**Issue by AdJones** [aurora-is-near/aurora-relayer#262]
**Describe the bug**
I have set up the NEAR account keys in the config directory as instructed (and modified mainnet.yaml to use the correct signer), but am getting an error when trying to send eth_sendRawTransaction. I am using Aurora MainNet.

The error:

Can not sign transactions for account satoshi.near on network mainnet, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryMultiKeyStore, InMemoryKeyStore, UnencryptedFileSystemKeyStore(/home/node/.near-credentials))).

**To Reproduce**
Steps to reproduce the behavior, e.g.:
- Change mainnet.yaml signer to correct wallet name, signerKeys pointing to the config/relayer.yaml, and add writable:true
- Change keys in the config/relayer.yaml to valid keys for the NEAR wallet
- docker-compose up to start the node
- Submit the eth_sendRawTransaction - observe error

**Expected behavior**
The transaction should not give this error

**Screenshots**

**Technical Details (please complete relevant fields):**
- Docker: yes
- Network MainNet
- Account: satoshi.near
- Browser: Firefox (Linux)
- RPC: Private/Local
- Technology: Nethereum/C#

**Additional context**

**Comment by luoxiandong** [comment]
I have same issue,Have you solved the problem？

**Comment by AdJones** [comment]
Not yet. I suspect the answer might be that you have to use `near-api-js` from here (although it would be nice if someone could confirm this): [https://github.com/near/near-api-js](https://github.com/near/near-api-js)

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
