### ISSUE TITLE
[BUG] eth_getBlockByNumber is returning block with dummy value of logsBloom

### ISSUE THREAD

**Issue by duongthienduc** [aurora-is-near/aurora-relayer#271]
**Describe the bug**
When call the method eth_getBlockByNumber, the returned value of logsBloom is `0x000...`

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Call the cUrl code: `curl https://testnet.aurora.dev/ -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x540d2a2", false],"id":273}'`
2. It returns: `..., logsBloom":"0x000...`

**Expected behavior**
The result of eth_getBlockByNumber should return bloom filter for the logs of the block

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
