### ISSUE TITLE
[ethjs-query] Transaction NaN failed! while formatting output from RPC

### ISSUE THREAD

**Issue by CryptoniteNodes** [aurora-is-near/aurora-relayer#274]
When testing the Borrow - Near - Borrow RUSD function, a bug occurs. It does not allow you to make any transactions
![image](https://user-images.githubusercontent.com/102903743/164894576-aead5d76-16ce-44c6-ae80-2deeeb137f2b.png)

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
