### ISSUE TITLE
Internal Error - invalid json response body at http://192.168.1.89:3030/ reason: Unexpected end of JSON input.

### ISSUE THREAD

**Issue by jsdude0220** [aurora-is-near/aurora-relayer#275]
When I call the contract function on aurora testnet, I am getting this error and not sure what is the reason.
![image](https://user-images.githubusercontent.com/58881761/165830591-cc238363-8b81-4eb3-9d0d-01a9d7d0d733.png)
The problem is that this error is just happened when I connect with deployer account only.
If I connect with another wallet account, the function works fine.

Please help me what is the reason.
Thanks.

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
