### ISSUE TITLE
Swap ETH to NEAR failed (on trisolaris.io)

### ISSUE THREAD

**Issue by Igor3003** [aurora-is-near/aurora-relayer#277]
**Describe the bug**
Swap ETH to NEAR failed (on trisolaris.io)

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Go to trisolaris.io
2. Click on swap
3. Chose ETH to wNEAR
4. Confirm transaction in Metamask
5. See error

Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - FetchError: invalid json response body at http://192.168.1.89:3030/ reason: Unexpected end of JSON input. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"r001.westcoast.us.relayer.internal.aurora.dev","cf-ray":"704acfbe815c9b46-SEA","request_body":{"id":8433594448802,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf90154808401c9c3808370d37c942cb45edb4517d5947

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
