### ISSUE TITLE
database is empty

### ISSUE THREAD

**Issue by rqzrqh** [aurora-is-near/aurora-relayer#279]
I use **NEAR_ENV=testnet docker-compose up** and all docker images start success.The relayer api always return blockNumber value is 0, I connect to the postgresql, it shows the database record count is 0 but tables are exist.
How can I download or restore the database record?

**Comment by rqzrqh** [comment]
My pc is MacBook M1 and the indexer always exit, however the indexer is responsible for writing database. I think I find the reason.

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
