### ISSUE TITLE
receipt log's topic content format error

### ISSUE THREAD

**Issue by rqzrqh** [aurora-is-near/aurora-relayer#280]
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockNumber": "0x3dfdf53",
    "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
    "transactionIndex": "0x0",
    "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
    "from": "0x8fd00e261ebb411fce5acc170a94c0cb67d7b869",
    "to": "0xf968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
    "gasUsed": "0x2c52f",
    "cumulativeGasUsed": "0x0",
    "contractAddress": null,
    "logs": [
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x0",
        "address": "0x885f8cf6e45bdd3fdcdc644efdcd0ac93880c781",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x000000000000000000000000c374776cf5c497adeef6b505588b00cb298531fd",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7"
        ],
        "data": "0x00000000000000000000000000000000000000000000011ff84359a1a520d2ec",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x1",
        "address": "0x885f8cf6e45bdd3fdcdc644efdcd0ac93880c781",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
          "0x0000000000000000000000001fd6cbbfc0363aa394bd77fc74f64009bf54a7e9"
        ],
        "data": "0x00000000000000000000000000000000000000000000011ff84359a1a520d2ec",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x2",
        "address": "0x4988a896b1227218e4a686fde5eabdcabd91571f",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x0000000000000000000000001fd6cbbfc0363aa394bd77fc74f64009bf54a7e9",
          "0x00000000000000000000000003b666f3488a7992b2385b12df7f35156d7b29cd"
        ],
        "data": "0x000000000000000000000000000000000000000000000000000000004f48f4fc",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x3",
        "address": "0x1fd6cbbfc0363aa394bd77fc74f64009bf54a7e9",
        "topics": [
          "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"
        ],
        "data": "0x0000000000000000000000000000000000000000000000000000000e6e2506b500000000000000000000000000000000000000000000356129b774069212807e",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x4",
        "address": "0x1fd6cbbfc0363aa394bd77fc74f64009bf54a7e9",
        "topics": [
          "0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
          "0x00000000000000000000000003b666f3488a7992b2385b12df7f35156d7b29cd"
        ],
        "data": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011ff84359a1a520d2ec000000000000000000000000000000000000000000000000000000004f48f4fc0000000000000000000000000000000000000000000000000000000000000000",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x5",
        "address": "0xc42c30ac6cc15fac9bd938618bcaa1a1fae8501d",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x00000000000000000000000003b666f3488a7992b2385b12df7f35156d7b29cd",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7"
        ],
        "data": "0x00000000000000000000000000000000000000000065af1983be526de351360a",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x6",
        "address": "0x03b666f3488a7992b2385b12df7f35156d7b29cd",
        "topics": [
          "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"
        ],
        "data": "0x00000000000000000000000000000000000000000000000000000af92acbd8d5000000000000000000000000000000000000000e1d3bfcc3b75332031091c2c2",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x7",
        "address": "0x03b666f3488a7992b2385b12df7f35156d7b29cd",
        "topics": [
          "0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7"
        ],
        "data": "0x000000000000000000000000000000000000000000000000000000004f48f4fc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000065af1983be526de351360a",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x8",
        "address": "0xc42c30ac6cc15fac9bd938618bcaa1a1fae8501d",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
          "0x000000000000000000000000c374776cf5c497adeef6b505588b00cb298531fd"
        ],
        "data": "0x000000000000000000000000000000000000000000635a665be0e9fa21140080",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0x9",
        "address": "0xc42c30ac6cc15fac9bd938618bcaa1a1fae8501d",
        "topics": [
          "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
          "0x000000000000000000000000d8e0f0c3bf475ad11da74eeb7b06d23dfb3c590f"
        ],
        "data": "0x0000000000000000000000000000000000000000000254b327dd6873c23d358a",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0xa",
        "address": "0xf968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
        "topics": null,
        "data": "0x01b57416f6012a0bc42c30ac6cc15fac9bd938618bcaa1a1fae8501d0000000254b327dd6873c23d358a",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0xb",
        "address": "0xc374776cf5c497adeef6b505588b00cb298531fd",
        "topics": [
          "0x1c411e9a96e071241c2f21f7726b17ae89e3cab4c78be50e062b03a9fffbbad1"
        ],
        "data": "0x000000000000000000000000000000000000000000026165b828d45809503d0c0000000000000000000000000000000000000000d201c744651e38bbd6534ea6",
        "removed": false
      },
      {
        "blockNumber": "0x3dfdf53",
        "blockHash": "0xd369a15a57899c0ff686243e5553d3f57ef5dc392f7252c7c43399bf0900c9a0",
        "transactionIndex": "0x0",
        "transactionHash": "0xd09dbc30579d2902ec6378ff5098b17b15aaa0ecac5bcd0ff5946bf64e55e7a4",
        "logIndex": "0xc",
        "address": "0xc374776cf5c497adeef6b505588b00cb298531fd",
        "topics": [
          "0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7",
          "0x000000000000000000000000f968ae76b67e0ac34ebd27dbe7157c43ec6124e7"
        ],
        "data": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000635a665be0e9fa2114008000000000000000000000000000000000000000000000011ff84359a1a520d2ec0000000000000000000000000000000000000000000000000000000000000000",
        "removed": false
      }
    ],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x1",
    "nearTransactionHash": "0xc1eb564dbb14cade16707dca77539def512cb5b2f74401a0e30b2e7336938c6f",
    "nearReceiptHash": "0xf36d04ca922159b9a85d4a74e97a607635b4c192fc9ef1245a1d2b103ddc2f8b"
  }
}

If use ethereum's golang module for request and unmarshal, always unmarshal failed.
The reason is 
 "topics": null, 

which is hopped for json-array, not json-null.

**Comment by zakerikk** [comment]
Hi @rqzrqh, we released a fix. Can you please check again?
