### ISSUE TITLE
Error: wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded))

### ISSUE THREAD

**Issue by apoorvsingal** [aurora-is-near/aurora-relayer#281]
Hey, is there a way we can configure the near node to allow higher gas limits than whatever's default? 

Calls like `contract.methods.someBigMethod.call({ gas: 1e18 })` currently throw a `wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded))` error and there's apparently no way around it. 

Full error log: 
```
Error: Returned error: Internal Error - Querying [object Object] failed: wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded)).
{
  "block_hash": "9pTg5KQVELmNo2ZArq8GhHjTFmzKEMiWkSPLvBtzmYQz",
  "block_height": 65175732,
  "error": "wasm execution failed with error: FunctionCallError(HostError(GasLimitExceeded))",
  "logs": []
}. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>
    at Object.ErrorResponse (errors.js?d2dd:28:1)
    at eval (index.js?b20e:300:1)
    at XMLHttpRequest.request.onreadystatechange (index.js?b231:98:1)
 ```

**Comment by aguirrel** [comment]
It's happening the same to me. Did you make it work?

**Comment by spilin** [comment]
@apoorvsingal , @aguirrel Thank you for submitting this. Can you please provide example of a contract so we can reproduce this.

**Comment by apoorvsingal** [comment]
https://docs.rari.capital/fuse/#get-pools-by-account-with-data This is one, it takes more gas than what aurora relayer allows (given the pools and assets count are high enough)

**Comment by vanpt1114** [comment]
After setting up my own self-hosted Aurora node (VM on cloud), I faced the same issue as above, but when I utilized public RPC, that error did not show up. Is there any further step that needs to be configured?

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
