### ISSUE TITLE
HardhatError: HH110: Invalid JSON-RPC response received - bug report

### ISSUE THREAD

**Issue by jsdude0220** [aurora-is-near/aurora-relayer#282]
Hey, I am getting the json-rpc error during deploy the contract, there was no error before 1 week, but recently I got invalid json-rpc error. here is error details and my hardhat config.
`HardhatError: HH110: Invalid JSON-RPC response received:`
![image](https://user-images.githubusercontent.com/58881761/167327413-0c0b93f4-f45a-4036-99e3-305019a86c95.png)

**Comment by svskaushik** [comment]
Hi, has there been some resolution to this?

I've been running into the same issue when trying to deploy to the testnet through hardhat.
Getting the following response: `524: A timeout occurred`
With this message: `The origin web server timed out responding to this request`

[Link ](https://github.com/svskaushik/Aurora-Lens-Subgraph/blob/d274b19f9da3a075aafd9fb1f03e8939b1f8e1d7/lens-protocol/hardhat.config.ts#L68) to hardhat config for reference

Any help appreciated,
Thanks

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
