### ISSUE TITLE
Docker images versioning 

### ISSUE THREAD

**Issue by qezz** [aurora-is-near/aurora-relayer#288]
Hi. I'm not really sure where to ask this, so let me know if there's a better place for this question/issue.

The issue is: Docker images don't have proper tags.
But a more broad question can be: How exactly aurora images are built?

I have two intentions, 

1. First is to pin the versions of these three images (`endpoint`, `database`, `nearcore`), so it is possible to keep track of the changes.
2. Secondly, to build the images on my own. Currently, I build them by running similar commands:

   ```bash
   git clone https://github.com/aurora-is-near/aurora-relayer && cd aurora-relayer
   git checkout <specific tag, e.g. 2022.05.17>
   ./.ci/setup.sh # to build 'testing' images
   export RUNNER_NAME="github-runner"
   ./.ci/setup.sh # to build 'prod' images

   # then I tag specific images with certain tags
   # e.g. aurora-endpoint:2022.05.17 or aurora-endpoint:mainnet-2022.05.17
   ```

   Not sure if it's a proper way to do this.

I was trying to understand how the images on Docker Hub are versioned and tagged, but I'm totally confused now. It seems like there are two main tags: `mainnet` and `testnet`, and on every update those are 'overwritten'.

I know it's possible to use image digests to pin a specific version of an image, but it's still not clear how to distinguish between releases.

More confusion is caused by the fact that some images are not updated even after a new 'release' happens. For example, `nearaurora/database:mainnet` image on docker hub was pushed 4 months ago.

I will be happy to realise that I'm wrong, and this issue is resolved already 🙂 

**Expected behavior**
* Each new image is tagged with a release tag or commit hash. For example `:mainnet-2022.05.17` or `:mainnet-97ed9aa`
* `latest` images point to the most recent release. In this case, it could be `mainnet` and `testnet`.

**Comment by spilin** [comment]
Hey, @qezz. This repository is deprecated. We released [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public). You can check [Standalone Aurora Relayer and Refiner](https://github.com/aurora-is-near/standalone-rpc) repo on how we build images.
