### ISSUE TITLE
[BUG]rpc failure for eth_getLogs when using topics

### ISSUE THREAD

**Issue by ClaudeZsb** [aurora-is-near/aurora-relayer#289]
**Describe the bug**
We just got an error for getting logs from this rpc: https://mainnet.aurora.dev
It said "Internal Error - syntax error at or near \"AND\". Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>"

**To Reproduce**
curl --request POST 'https://mainnet.aurora.dev' \
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_getLogs",
        "params":[{
          "address":[
                "0xc1a2D967DfAa6A10f3461bc21864C23C1DD51EeA"
          ],
          "fromBlock":"0x3ecdf57",
          "toBlock":"0x3ece307",
                "topics":[[],["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"]]
        }],
        "id":74
}'

**Expected behavior**
I tried the same curl command on ethereum. And it works. 

**Screenshots**

<img width="650" alt="截屏2022-05-20 下午6 37 02" src="https://user-images.githubusercontent.com/29391243/169510957-19b5ec2e-3091-488c-a801-1fc7249c5d09.png">

**Comment by zakerikk** [comment]
Hi @ClaudeZsb, we released a fix. Can you please check again?

**Comment by ClaudeZsb** [comment]
thx guys. it looks good now.
