### ISSUE TITLE
Invalid RPC response, 524: A timeout occurred

### ISSUE THREAD

**Issue by svskaushik** [aurora-is-near/aurora-relayer#296]
Hi,

I've been running into `Error HH110: Invalid JSON-RPC response received` when trying to deploy to the testnet through hardhat.
Getting the following response: `524: A timeout occurred`
With this message: `The origin web server timed out responding to this request`

Using this endpoint : `https://testnet.aurora.dev`

[Link ](https://github.com/svskaushik/Aurora-Lens-Subgraph/blob/d274b19f9da3a075aafd9fb1f03e8939b1f8e1d7/lens-protocol/hardhat.config.ts#L68) to hardhat config for reference

It seems that I'm not the only one experiencing these issues with the testnet as [Chainlist](https://chainlist.org/) also looks like it's having connection issues:
![image](https://user-images.githubusercontent.com/92371232/170815212-616f32f4-ee44-461c-835e-d18f5926ba86.png)

Any help appreciated, (@think-in-universe, I needed this for ETH Shanghai so I'd really appreciate a quicker resolution, though I don't mean to burden resources if people aren't free)
Thanks

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
