### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lwightmoon** [aurora-is-near/aurora-relayer#298]
**Describe the bug**
call erc20's method balanceOf occur errors
error msg:
Internal Error - [-32000] Server error: The node reached its limits. Try again later. More details: StorageInconsistentState("Trie node missing")

eg:
erc20 contract:0xdDAdf88b007B95fEb42DDbd110034C9a8e9746F2
addr:0x1aE62F41dd7ABFd106234564A97f70c89886CB93

**To Reproduce**
Steps to reproduce the behavior, e.g.:
use multicall to call erc20's balanceOf

**Expected behavior**

**Screenshots**

**Technical Details (please complete relevant fields):**
- NEARcore commit/branch
- Rust version (if local)
- Docker (if using docker)
- Mainnet/Testnet/Betanet/local
- Name of the dApp used
- Wallet name and version
- Browser name and version
- Tokens used
- RPC Public/Private
- Technology used (JS, TS, etc.)
- Gas related issue — Yes/No

**Additional context**

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
