### ISSUE TITLE
RCP for Aurora testnet is slow and unstable #516[BUG]

### ISSUE THREAD

**Issue by birinets** [aurora-is-near/aurora-relayer#302]
testnet.aurora.dev is very slow and in many cases giving timeout.
When doing transaction via Metamask in transaction is processed on explorer but in Metamask it is still processing for few min.

**Comment by KenWang1** [comment]
agree, I got timeout many times

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
