### ISSUE TITLE
[testnet] wss log requests are not available

### ISSUE THREAD

**Issue by ehdwls19** [aurora-is-near/aurora-relayer#320]
Hi, guys I'm working on get logs from wss on tesetnet. 

It worked fine when I change rpc address to mainnet one, but it doesn't work with testnet rpc address.
The deployed token contract obviously has an emit for transfer event. 
And I transferred token about 10 times while this code was running, but it doens't show any logs.

Any issues with testnet? or is there any solutions for this?

Here is the code to get logs from wss.

```const Web3 = require("web3");
const web3 = new Web3(
  new Web3.providers.WebsocketProvider("wss://testnet.aurora.dev/")
);
const transferHash = web3.utils.keccak256("Transfer(address,address,uint256)");
console.log(transferHash);
var subscription = web3.eth
  .subscribe(
    "logs",
    {
      address: "", //token Address
      topics: [transferHash, null, null],
    },
    function (error, result) {
      if (!error) {
        console.log(result);
      }
    }
  )
  .on("connected", function (subscriptionId) {
    console.log(subscriptionId);
  })
  .on("data", function (log) {
    console.log(log);
  })
  .on("changed", function (log) {});
subscription.unsubscribe(function (error, success) {
  if (success) console.log("Successfully unsubscribed!");
});```

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
