### ISSUE TITLE
[BUG] eth_sendRawTransaction success, but  cannot find the tx

### ISSUE THREAD

**Issue by bobbychen** [aurora-is-near/aurora-relayer#333]
**Describe the bug**
 eth_sendRawTransaction success, but cannot find the tx on the explorer. (mainnet: https://mainnet.aurora.dev/)

this is request body:
{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86d0884042c1d80826d6094aa258f57fdc3a63c57fedb4c020b1eaa46cc9111865af3107a400080849c8a82c8a099d4f6c886396d09531e25bc01e72cbc25b6dd74b624f35155b1506e81c6452ba00ba411e74dcd645f8e865247067a66f612557d77a039514f3377b5f9443b941e"],"id":"1"} 

the return is:
{"jsonrpc":"2.0","id":"1","result":"0x5e46b1f87a9e35a03fd5da200242f2b2ce9abde86e26e8d7064ef6e794b460a2"}

**Comment by birchmd** [comment]
Thanks for the report @bobbychen 

There are occasionally transient issues which result in transactions being dropped. If you experience this issue again please wait a few minutes and try resending your transaction.

We resent your transaction using the request body you posted here and the transaction went through: https://aurorascan.dev/tx/0x5e46b1f87a9e35a03fd5da200242f2b2ce9abde86e26e8d7064ef6e794b460a2

**Comment by TanyaSrivastava-Dipali** [comment]
@bobbychen Could You please share the code for  eth_sendRawTransaction
