### ISSUE TITLE
[FEATURE] Fix image releases to Docker Hub

### ISSUE THREAD

**Issue by vorotech** [aurora-is-near/aurora-relayer#335]
**Is your feature request related to a problem? Please describe.**
The instruction to run docker-compose.yml doesn't seem to work – it is referring to images pushed to Docker Hub 7 month ago.

**Describe the solution you'd like**
Update remote Docker images when new release/tag is created.

**Describe alternatives you've considered**
Alternatively, the whole project can be build with custom docker-compose which has build context specified.
But it could be too complicated for the chain developers.

**Comment by vorotech** [comment]
Probably duplication of https://github.com/aurora-is-near/aurora-relayer/issues/288

**Comment by spilin** [comment]
his repository is deprecated. We released [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public). You can check [Standalone Aurora Relayer and Refiner](https://github.com/aurora-is-near/standalone-rpc) repo on how we build images. We updated docker containers.
