### ISSUE TITLE
[FEATURE] Please enable trace mode

### ISSUE THREAD

**Issue by rootsha256** [aurora-is-near/aurora-relayer#339]
I'm trying to deploy sushi masterchef subgraph on aurora but failed to run with message
Failed to start subgraph, code: SubgraphStartFailure, error: expected triggers adapter that matches deployment QmVqjnUaMLVXUQVwdijS7EvXNgbx94yvX5ZejRwgwH5C2y[405538] with required capabilities: archive, traces: A matching Ethereum network with NodeCapabilities { archive: true, traces: true } was not found.

**Comment by pustovalov** [comment]
Hi @rootsha256 

Do you a have a reproduction repo you can share? It will help to fix the issue

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
