### ISSUE TITLE
Error: Returned error: Internal Error - . Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>

### ISSUE THREAD

**Issue by ctindogaru** [aurora-is-near/aurora-relayer#340]
This only started to happen 2-3 days ago. I'm using WebSocketProvider("wss://testnet.aurora.dev") to make smart contract calls on Aurora Testnet. Recently, I keep getting:
```
Uncaught (in promise) Error: Error: Returned error: Internal Error - . Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>
    at utils.ts:294:1
```

Is there something wrong with the network? Is it related to the Ethereum merge?

**Comment by vladikopl01** [comment]
I had the same problem with my contract getters which is called by hand with some arguments. But on page load, some getters with no arguments which is called by default get the right data from the contract.

![image](https://user-images.githubusercontent.com/56199219/195374312-7934e524-337e-4aac-a04d-7dac00395137.png)

[Link to the contract](https://testnet.aurorascan.dev/address/0x4def71e725d2a7c910721a1750b5aef97f50fda1#readProxyContract)

**Comment by pustovalov** [comment]
Hi @ctindogaru @vladikopl01 

Are you still encountering this issue?

**Comment by vladikopl01** [comment]
> Hi @ctindogaru @vladikopl01 
> 
> 
> 
> Are you still encountering this issue?

This problem seems to be resolved after 2-5 days. I think there were some troubles with the testnet, but now it should work. I deployed a smart contract a few days ago and it worked correctly.

**Comment by pustovalov** [comment]
Thx, please reopen if it will reoccur.
