### ISSUE TITLE
net_version should return decimal number

### ISSUE THREAD

**Issue by 0x3bfc** [aurora-is-near/aurora-relayer#40]
The `net_version` RPC returns hex representation for the chainId. But it should be in a decimal format.

References:
- https://eth.wiki/json-rpc/API
- https://infura.io/docs/ethereum/json-rpc/net-version

**Comment by antonpaisov** [comment]
The problem is that in `net_version` we're in fact returning the return value of `eth_chainId` call.
But the EIP https://eips.ethereum.org/EIPS/eip-695 doesn't state that the traditional value of `net_version` should be modified.
