### ISSUE TITLE
get block timestamp fails

### ISSUE THREAD

**Issue by 0x3bfc** [aurora-is-near/aurora-relayer#50]
Troubleshooting the `block.timestamp` on Aurora

Example:

https://github.com/makerdao/multicall/blob/1e1b44362640820bef92d0ccf5eeee25d9b41474/src/Multicall.sol#L36

An error due to microsecond timestamp:
https://explorer.near.org/transactions/GUEyK9H9RevA2MP74q1LGfKoY4s9y74MFiKz3G5tSD8D

**Comment by 0x3bfc** [comment]
Blocked by aurora-engine update https://github.com/aurora-is-near/aurora-engine/pull/287

**Comment by antonpaisov** [comment]
@0x3bfc isn't this already fixed?

**Comment by 0x3bfc** [comment]
Fixed and tested in the engine.
