### ISSUE TITLE
Move near_* to Aurora non-standard RPC

### ISSUE THREAD

**Issue by 0x3bfc** [aurora-is-near/aurora-relayer#51]
Remove the Near block hash and Near transaction hash from the standard RPC methods. It has implications on the explorer where it is expecting a specific transaction and block formats.

https://github.com/aurora-is-near/aurora-relayer/blob/d572f7b425572a59e5826fe42eaa986bf9e3c47e/src/indexer.ts#L101

**Comment by mfornet** [comment]
@paouvrard I understand we are using `near_hash` in the frontend. I think it should be possible to have several methods, one where we stick to the current specification from ethereum RPC, and new methods where we have the possibility to augment this information with new information. 

This way it will be simpler to integrate with other tools that expects a format from our RPC.

**Comment by 0x3bfc** [comment]
Thanks @mfornet for clarifying the issue. After discussing this with @paouvrard, he asked it would be great to have the new non-standard RPC method callable with `ethersProvider.send()`.

So I will test it first before going to start it working on it.

**Comment by artob** [comment]
> It has implications on the explorer where it is expecting a specific transaction and block formats.

@0x3bfc Meaning, the extra fields are concretely confusing BlockScout?

> I will discuss with @artob the alternatives we can have to keep the database scheme as is.

@0x3bfc The schema per se will remain as is, you just need to add a new stored procedure by copying the existing one and renaming it, and then removing the extra non-standard fields from the output of the original, standard stored procedure.

**Comment by 0x3bfc** [comment]
> @0x3bfc Meaning, the extra fields are concretely confusing BlockScout?

Based on the feedback from @mfornet Yes.
