### ISSUE TITLE
MetaMask error but transaction was actually broadcasted.

### ISSUE THREAD

**Issue by paouvrard** [aurora-is-near/aurora-relayer#58]
A TG user making an Aurora tx got a failed transaction in MetaMask but the transaction was actually executed and succeeded. The bridge app couldn't recognize that a tx was made so the transfer needed to be restored.

<img width="311" alt="å¾®ä¿¡å¾ç_20211016005506" src="https://user-images.githubusercontent.com/29397451/137571343-d09930c0-b04d-4d03-93a1-2425b635bf20.png">

**Comment by johni1228** [comment]
So did you fixe that issue?

**Comment by spilin** [comment]
should be fixed now, please reopen if it will occurs again
