### ISSUE TITLE
swap failed

### ISSUE THREAD

**Issue by echoamireux** [aurora-is-near/aurora-relayer#59]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Exceeded the maximum amount of gas allowed to burn per contract.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"mainnet.aurora.dev","cf-ray":"6a0307d806161f9f-ORD"}}}}'

**Comment by 0x3bfc** [comment]
duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
