### ISSUE TITLE
Swap near to dai

### ISSUE THREAD

**Issue by ff091** [aurora-is-near/aurora-relayer#72]
![image](https://user-images.githubusercontent.com/4956569/138593042-71abaca1-61ff-4d26-86ee-2cd1f292dab8.png)

**Comment by VaporwaveFinance** [comment]
This error occurs often on our autocomp harvesters. 

Error: 

`Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":6573,\"error\":{\"code\":-32603,\"message\":\"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>\",\"data\":{\"host\":\"relayer006.backend.internal.aurora.dev\",\"cf-ray\":\"6ce5260e86ef5c77-PDX\"}}}", error={"code":-32603,"data":{"host":"relayer006.backend.internal.aurora.dev","cf-ray":"6ce5260e86ef5c77-PDX"}}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf86a82b6c880837a1200949b62d0aaa0c2321b38431beaae64c2d2ed9308368084c15fc688849c8a82c7a0331f4b7ef33b18c945c8a92c2e4d888958078c185c7a4a9cab3374a923414ee8a02ded38ac59d1503e64e41d3fb2e925f72f345ceb34d98a7caf4a65e61bcb4829\"],\"id\":6573,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://mainnet.aurora.dev", code=SERVER_ERROR, version=web/5.5.1)`

Using:
```
      "axios": "^0.21.1",
      "bignumber.js": "^9.0.1",
      "eth-multicall": "^1.3.13",
      "dotenv": "^10.0.0",
      "ethers": "5.5.3",
      "ethers-multicall": "^0.2.0",
      "web3": "^1.5.0"
```

**Comment by wangdayong228** [comment]
Is this issue resolved? I always meet this issue and could not send batch transactions at all, is there any way to avoid this?

**Comment by spilin** [comment]
This repository is deprecated. If issue still persists, please reopen it on a new repository of [Aurora Relayer v2](https://github.com/aurora-is-near/relayer2-public).
