### ISSUE TITLE
Unable to transfer NEAR from AURORA to NEAR

### ISSUE THREAD

**Issue by kiemtienonline360** [aurora-is-near/aurora-relayer#73]
I am unable to transfer NEAR from AURORA. This error message is as below image:
![aurora_bridge](https://user-images.githubusercontent.com/12036697/138601573-77863004-9308-4a0f-9e5d-9b51fd42c09a.png)
e!

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/72
