### ISSUE TITLE
have Error during swap

### ISSUE THREAD

**Issue by HienNguyen2711** [aurora-is-near/aurora-relayer#74]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/72
