### ISSUE TITLE
Issue when swapping from wNear to ETH in trisolaris.io

### ISSUE THREAD

**Issue by TienNLN** [aurora-is-near/aurora-relayer#75]
![image](https://user-images.githubusercontent.com/44812709/138618396-5922b32c-238d-4bcd-a84c-1588d71a39db.png)

I met some trouble when swapping from wNear to ETH in trisolaris.io. But the next time I tried, there is no such a bug like that again (I think this issue just sometimes happens)

**Comment by 0x3bfc** [comment]
duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
