### ISSUE TITLE
Failed to swap on trisolaris.io  #Error: nonce retries exceeded for transaction

### ISSUE THREAD

**Issue by vanminh2501** [aurora-is-near/aurora-relayer#77]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"mainnet.aurora.dev","cf-ray":"6a38203ed0aec6b0-PHX"}}}}

![Screen Shot 2021-10-25 at 09 53 40](https://user-images.githubusercontent.com/5908334/138627882-3335b6ee-07f9-4dcd-9104-bf6d8b6628f6.png)
'

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/72
