### ISSUE TITLE
It takes too long to swap from ETH to wNEAR

### ISSUE THREAD

**Issue by ouisado** [aurora-is-near/aurora-relayer#79]
The transaction is pending too long, approximately 18 hours and it is still pending.
https://explorer.mainnet.aurora.dev/tx/0xd6a28c80e2ab46fe37144b89d3464bde6d3bcc69a55019c2ef20ca0616128c87/logs

**Comment by 0x3bfc** [comment]
There is no enough information to test this issue. Please feel free to reopen it with more info.
