### ISSUE TITLE
Internal Error - BadGatewayError when I swaped wnear-usdt after swaped wnear-dai

### ISSUE THREAD

**Issue by myhao91** [aurora-is-near/aurora-relayer#80]
The response:

{
  "value": {
    "code": -32603,
    "data": {
      "code": -32603,
      "message": "Internal Error - BadGatewayError: \n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>",
      "data": {
        "host": "mainnet.aurora.dev",
        "cf-ray": "6a390154b7c1248d-HKG"
      }
    }
  }
}

My wallet explorer: https://explorer.mainnet.aurora.dev/address/0x55B9310Aff23c9E7bb5ed7215BbfE09EA26C0c97/transactions

**Comment by 0x3bfc** [comment]
This issue was resolved please try again.
