### ISSUE TITLE
Can't swap ETH to wNear on https://www.trisolaris.io/#/swap

### ISSUE THREAD

**Issue by ukenty** [aurora-is-near/aurora-relayer#83]
![Cannot swap](https://user-images.githubusercontent.com/93127278/138677983-99ba8858-7c12-4029-bf61-deb27cf86a69.jpg)

I have an issue, can't swap ETH to wNear.
what should i do?

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/72
