### ISSUE TITLE
lỗi khi swap

### ISSUE THREAD

**Issue by adamtem1** [aurora-is-near/aurora-relayer#85]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"mainnet.aurora.dev","cf-ray":"6a3adc3e44243cf4-ORD"}}}}'

**Comment by 0x3bfc** [comment]
No enough information here. Feel free to reopen the issue if you still get the same error.
