### ISSUE TITLE
The transaction is successful but in trisolaris, transaction still pending

### ISSUE THREAD

**Issue by HienNguyen2711** [aurora-is-near/aurora-relayer#86]
Hashtash: 0x129b034ec0da19396e2032f6520817607bd273ab326ac7a03368ddeadd647228 
Status = success.
However, transaction in trisolaris is still pending
![image](https://user-images.githubusercontent.com/13329657/138683699-a86b83a6-f02a-4283-988f-a8137239771a.png)

**Comment by 0x3bfc** [comment]
We don't know, please iterate with Trisolaris why the transaction is pending from their side. Everything seems to be correct here https://explorer.mainnet.aurora.dev/tx/0x129b034ec0da19396e2032f6520817607bd273ab326ac7a03368ddeadd647228/logs
