### ISSUE TITLE
Swap error from wNear to ETH

### ISSUE THREAD

**Issue by YorkVPS** [aurora-is-near/aurora-relayer#88]
![screenshot_1635162947](https://user-images.githubusercontent.com/79439305/138690746-d71aa3dc-e0e6-4518-adab-d1817f100bbf.png)

**Comment by 0x3bfc** [comment]
This is a duplicate issue please refer to this issue https://github.com/aurora-is-near/aurora-relayer/issues/60 

Will keep you updated whenever the max gas amount upgraded in NEAR.
