### ISSUE TITLE
Swap failed ETH -> WNEAR: [ethjs-query] while formatting outputs from RPC

### ISSUE THREAD

**Issue by nguyentrungnghia98** [aurora-is-near/aurora-relayer#91]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: nonce retries exceeded for transaction. This usually means there are too many parallel requests with the same access key.. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"mainnet.aurora.dev","cf-ray":"6a3ceede41684c53-SIN"}}}}'

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/72
