### ISSUE TITLE
Swap failed: [ethjs-query]

### ISSUE THREAD

**Issue by dtnam1997** [aurora-is-near/aurora-relayer#92]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - Error: Transaction has expired. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"mainnet.aurora.dev","cf-ray":"6a3d472631e04df8-SIN"}}}}'

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/87
