### ISSUE TITLE
Can't do any token swap

### ISSUE THREAD

**Issue by vantoanbk57** [aurora-is-near/aurora-relayer#94]
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32603,"message":"Internal Error - [-32000] Server error: DB Not Found Error: BLOCK HEIGHT: 51104598 \n Cause: Unknown. Please report a bug at <https://github.com/aurora-is-near/aurora-relayer/issues>","data":{"host":"mainnet.aurora.dev","cf-ray":"6a3ff782023c6e52-ORD"}}}}'

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/68
