### ISSUE TITLE
Swap wnear to dai error

### ISSUE THREAD

**Issue by ff091** [aurora-is-near/aurora-relayer#95]
Error message:
Swap failed: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32601,"message":"Unsupported method: eth_sendRawTransaction","data":{"host":"mainnet.aurora.dev","cf-ray":"6a40482c158cc6b4-HAN"}}}}'

**Comment by spilin** [comment]
you were temporarily banned, this is no longer relevant
