### ISSUE TITLE
issue when swap eth to wnear

### ISSUE THREAD

**Issue by duyphan124** [aurora-is-near/aurora-relayer#96]
Wallet: duyphan124.near

<img width="1430" alt="Screen Shot 2021-10-27 at 02 15 03" src="https://user-images.githubusercontent.com/84948484/138947239-ec008607-8951-43db-ba79-b5c31f5e6ad3.png">

**Comment by 0x3bfc** [comment]
duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
