### ISSUE TITLE
issue when swap from wNEAR to USDC and USDT

### ISSUE THREAD

**Issue by thanhtung2105** [aurora-is-near/aurora-relayer#98]
NEAR Wallet: kentphan.near
Aurora Wallet: 0x5445b27EeEA00F196bB933dA26937C809746a003

![image](https://user-images.githubusercontent.com/48848418/139038163-1592f9bc-2600-4bd1-911e-31bc69177ed5.png)

**Comment by 0x3bfc** [comment]
Please check the rainbow bridge repos for these kind of issues.
