### ISSUE TITLE
issue when swap from wNEAR to ETH

### ISSUE THREAD

**Issue by thanhtung2105** [aurora-is-near/aurora-relayer#99]
NEAR wallet: kentphan.near
Aurora wallet: 0x5445b27EeEA00F196bB933dA26937C809746a003

![image](https://user-images.githubusercontent.com/48848418/139039037-857f77dd-279e-46c2-8734-d08f7249031f.png)

**Comment by 0x3bfc** [comment]
Duplicate issue https://github.com/aurora-is-near/aurora-relayer/issues/60
